#lang racket/base

(require redex/reduction-semantics
         "base-lang.rkt")

(define-syntax-rule (define-funtype-table funtype-table
                      [name (case-> case ...)]
                      ...)
  (begin
    (cond
      [(not (operator? (term name)))
       (error 'define-funtype-table "~a is not an operator" 'name)]
      [(not (arrow? (term case)))
       (error 'define-funtype-table "~a is not a valid arrow"
              'case)]
      ...)
    ...
    (define funtype-table
      (make-immutable-hash (list (cons (term name) (term (case-> case ...))) ...)))))

(define-funtype-table
  syntactic-funtype-table
  [add1 (case->
         (-> (Zero) (One))
         (-> (One) (Positive-Byte))
         (-> (Byte) (Positive-Index))
         (-> (Index) (Positive-Fixnum))
         (-> (Negative-Fixnum) (Nonpositive-Fixnum))
         (-> (Nonpositive-Fixnum) (Fixnum))
         (-> (Nonnegative-Integer) (Positive-Integer))
         (-> (Negative-Integer) (Nonpositive-Integer))
         (-> (Integer) (Integer))
         (-> (Nonnegative-Rational) (Positive-Rational))
         (-> (Rational) (Rational))
         (-> (Nonnegative-Float) (Positive-Float))
         (-> (Float) (Float))
         (-> (Nonnegative-Single-Float) (Positive-Single-Float))
         (-> (Single-Float) (Single-Float))
         (-> (Nonnegative-Inexact-Real) (Positive-Inexact-Real))
         (-> (Inexact-Real) (Inexact-Real))
         (-> (Nonnegative-Real) (Positive-Real))
         (-> (Real) (Real))
         (-> (Float-Complex) (Float-Complex))
         (-> (Single-Float-Complex) (Single-Float-Complex))
         (-> (Inexact-Complex) (Inexact-Complex))
         (-> (Number) (Number)))]
  [+ (case->
      (-> (Number Zero) (Number))
      (-> (Zero Number) (Number))
      (-> (Positive-Byte Positive-Byte) (Positive-Index))
      (-> (Byte Byte) (Index))
      (-> (Positive-Byte Positive-Byte) (Positive-Index))
      (-> (Positive-Index Index) (Positive-Fixnum))
      (-> (Index Positive-Index) (Positive-Fixnum))
      (-> (Index Index) (Nonnegative-Fixnum))
      (-> (Negative-Fixnum One) (Nonpositive-Fixnum))
      (-> (One Negative-Fixnum) (Nonpositive-Fixnum))
      (-> (Nonpositive-Fixnum Nonnegative-Fixnum) (Fixnum))
      (-> (Nonnegative-Fixnum Nonpositive-Fixnum) (Fixnum))
      (-> (Positive-Integer Nonnegative-Integer) (Positive-Integer))
      (-> (Nonnegative-Integer Positive-Integer) (Positive-Integer))
      (-> (Negative-Integer Nonpositive-Integer) (Negative-Integer))
      (-> (Nonpositive-Integer Negative-Integer) (Negative-Integer))
      (-> (Nonnegative-Integer Nonnegative-Integer) (Nonnegative-Integer))
      (-> (Nonpositive-Integer Nonpositive-Integer) (Nonpositive-Integer))
      (-> (Integer Integer) (Integer))
      (-> (Positive-Rational Nonnegative-Rational) (Positive-Rational))
      (-> (Nonnegative-Rational Positive-Rational) (Positive-Rational))
      (-> (Negative-Rational Nonpositive-Rational) (Negative-Rational))
      (-> (Nonpositive-Rational Negative-Rational) (Negative-Rational))
      (-> (Nonnegative-Rational Nonnegative-Rational) (Nonnegative-Rational))
      (-> (Nonpositive-Rational Nonpositive-Rational) (Nonpositive-Rational))
      (-> (Rational Rational) (Rational))
      (-> (Positive-Float Nonnegative-Real) (Positive-Float))
      (-> (Nonnegative-Real Positive-Float) (Positive-Float))
      (-> (Positive-Real Nonnegative-Float) (Positive-Float))
      (-> (Nonnegative-Float Positive-Real) (Positive-Float))
      (-> (Negative-Float Nonpositive-Real) (Negative-Float))
      (-> (Nonpositive-Real Negative-Float) (Negative-Float))
      (-> (Negative-Real Nonpositive-Float) (Negative-Float))
      (-> (Nonpositive-Float Negative-Real) (Negative-Float))
      (-> (Nonnegative-Float Nonnegative-Real) (Nonnegative-Float))
      (-> (Nonnegative-Real Nonnegative-Float) (Nonnegative-Float))
      (-> (Nonpositive-Float Nonpositive-Real) (Nonpositive-Float))
      (-> (Nonpositive-Real Nonpositive-Float) (Nonpositive-Float))
      (-> (Float Real) (Float))
      (-> (Real Float) (Float))
      (-> (Float Float) (Float))
      (-> (Positive-Single-Float (union Nonnegative-Rational Nonnegative-Single-Float)) (Positive-Single-Float))
      (-> ((union Nonnegative-Rational Nonnegative-Single-Float) Positive-Single-Float) (Positive-Single-Float))
      (-> ((union Positive-Rational Positive-Single-Float) Nonnegative-Single-Float) (Positive-Single-Float))
      (-> (Nonnegative-Single-Float (union Positive-Rational Positive-Single-Float)) (Positive-Single-Float))
      (-> (Negative-Single-Float (union Nonpositive-Rational Nonpositive-Single-Float)) (Negative-Single-Float))
      (-> ((union Nonpositive-Rational Nonpositive-Single-Float) Negative-Single-Float) (Negative-Single-Float))
      (-> ((union Negative-Rational Negative-Single-Float) Nonpositive-Single-Float) (Negative-Single-Float))
      (-> (Nonpositive-Single-Float (union Negative-Rational Negative-Single-Float)) (Negative-Single-Float))
      (-> (Nonnegative-Single-Float (union Nonnegative-Rational Nonnegative-Single-Float)) (Nonnegative-Single-Float))
      (-> ((union Nonnegative-Rational Nonnegative-Single-Float) Nonnegative-Single-Float) (Nonnegative-Single-Float))
      (-> (Nonpositive-Single-Float (union Nonpositive-Rational Nonpositive-Single-Float)) (Nonpositive-Single-Float))
      (-> ((union Nonpositive-Rational Nonpositive-Single-Float) Nonpositive-Single-Float) (Nonpositive-Single-Float))
      (-> (Single-Float (union Rational Single-Float)) (Single-Float))
      (-> ((union Rational Single-Float) Single-Float) (Single-Float))
      (-> (Single-Float Single-Float) (Single-Float))
      (-> (Positive-Inexact-Real Nonnegative-Real) (Positive-Inexact-Real))
      (-> (Nonnegative-Real Positive-Inexact-Real) (Positive-Inexact-Real))
      (-> (Positive-Real Nonnegative-Inexact-Real) (Positive-Inexact-Real))
      (-> (Nonnegative-Inexact-Real Positive-Real) (Positive-Inexact-Real))
      (-> (Negative-Inexact-Real Nonpositive-Real) (Negative-Inexact-Real))
      (-> (Nonpositive-Real Negative-Inexact-Real) (Negative-Inexact-Real))
      (-> (Negative-Real Nonpositive-Inexact-Real) (Negative-Inexact-Real))
      (-> (Nonpositive-Inexact-Real Negative-Real) (Negative-Inexact-Real))
      (-> (Nonnegative-Inexact-Real Nonnegative-Real) (Nonnegative-Inexact-Real))
      (-> (Nonnegative-Real Nonnegative-Inexact-Real) (Nonnegative-Inexact-Real))
      (-> (Nonpositive-Inexact-Real Nonpositive-Real) (Nonpositive-Inexact-Real))
      (-> (Nonpositive-Real Nonpositive-Inexact-Real) (Nonpositive-Inexact-Real))
      (-> (Inexact-Real Real) (Inexact-Real))
      (-> (Real Inexact-Real) (Inexact-Real))
      (-> (Positive-Real Nonnegative-Real) (Positive-Real))
      (-> (Nonnegative-Real Positive-Real) (Positive-Real))
      (-> (Negative-Real Nonpositive-Real) (Negative-Real))
      (-> (Nonpositive-Real Negative-Real) (Negative-Real))
      (-> (Nonnegative-Real Nonnegative-Real) (Nonnegative-Real))
      (-> (Nonpositive-Real Nonpositive-Real) (Nonpositive-Real))
      (-> (Real Real) (Real))
      (-> (Exact-Number Exact-Number) (Exact-Number))
      (-> (Float-Complex Number) (Float-Complex))
      (-> (Number Float-Complex) (Float-Complex))
      (-> (Float Inexact-Complex) (Float-Complex))
      (-> (Inexact-Complex Float) (Float-Complex))
      (-> (Single-Float-Complex (union Rational Single-Float Single-Float-Complex)) (Single-Float-Complex))
      (-> ((union Rational Single-Float Single-Float-Complex) Single-Float-Complex) (Single-Float-Complex))
      (-> (Inexact-Complex (union Rational Inexact-Real Inexact-Complex)) (Inexact-Complex))
      (-> ((union Rational Inexact-Real Inexact-Complex) Inexact-Complex) (Inexact-Complex)))])
