#lang racket/base

(require redex/reduction-semantics
         "base-lang.rkt")

(define-syntax-rule (define-funtype name body)
  (begin
    (define-term name body)
    (unless (funtype? (term name))
      (error 'define-funtype "~a is not a funtype" 'name))))

(define-funtype type-of-add1
  (case->
   (-> (Zero) (One))
   (-> (One) (Positive-Byte))
   (-> (Byte) (Positive-Index))
   (-> (Index) (PositiveFixnum))
   (-> (Negative-Fixnum) (Nonpositive-Fixnum))
   (-> (Nonpositive-Fixnum) (Fixnum))
   (-> (NonnegativeInteger) (Positive-Integer))
   (-> (NegativeInteger) (NonpositiveInteger))
   (-> (Integer) (Integer))
   (-> (Nonnegative-Rational) (Positive-Rational))
   (-> (Rational) (Rational))
   (-> (Nonnegative-Float) (Positive-Float))
   (-> (Float) (Float))
   (-> (Nonnegative-Single-Float) (Positive-Single-Float))
   (-> (Single-Float) (Single-Float))
   (-> (Nonnegative-InexactReal) (Positive-InexactReal))
   (-> (InexactReal) (InexactReal))
   (-> (Nonnegative-Real) (Positive-Real))
   (-> (Real) (Real))
   (-> (Float-Complex) (Float-Complex))
   (-> (Single-Float-Complex) (Single-Float-Complex))
   (-> (Inexact-Complex) (Inexact-Complex))
   (-> (Number) (Number))))

(define-funtype type-of-+
  (case->
   (-> Number Zero Number)
   (-> Zero Number Number)
   (-> Positive-Byte Positive-Byte Positive-Index)
   (-> Byte Byte Index)
   (-> Positive-Byte Positive-Byte Positive-Byte Positive-Index)
   (-> Byte Byte Byte Index)
   (-> Positive-Index Index PositiveFixnum)
   (-> Index Positive-Index PositiveFixnum)
   (-> Positive-Index Index Index PositiveFixnum)
   (-> Index Positive-Index Index PositiveFixnum)
   (-> Index Index Positive-Index PositiveFixnum)
   (-> Index Index Nonnegative-Fixnum)
   (-> Index Index Index Nonnegative-Fixnum)
   (-> Negative-Fixnum One Nonpositive-Fixnum)
   (-> One Negative-Fixnum Nonpositive-Fixnum)
   (-> Nonpositive-Fixnum Nonnegative-Fixnum Fixnum)
   (-> Nonnegative-Fixnum Nonpositive-Fixnum Fixnum)
   (-> PositiveInteger NonnegativeInteger PositiveInteger)
   (-> NonnegativeInteger PositiveInteger PositiveInteger)
   (-> NegativeInteger NonpositiveInteger NegativeInteger)
   (-> NonpositiveInteger NegativeInteger NegativeInteger)
   (-> NonnegativeInteger NonnegativeInteger NonnegativeInteger)
   (-> NonpositiveInteger NonpositiveInteger NonpositiveInteger)
   (-> Integer Integer Integer)
   (-> Positive-Rational Nonnegative-Rational Positive-Rational)
   (-> Nonnegative-Rational Positive-Rational Positive-Rational)
   (-> Negative-Rational Nonpositive-Rational Negative-Rational)
   (-> Nonpositive-Rational Negative-Rational Negative-Rational)
   (-> Nonnegative-Rational Nonnegative-Rational Nonnegative-Rational)
   (-> Nonpositive-Rational Nonpositive-Rational Nonpositive-Rational)
   (-> Rational Rational Rational)
   (-> Positive-Float Nonnegative-Real Positive-Float)
   (-> Nonnegative-Real Positive-Float Positive-Float)
   (-> Positive-Real Nonnegative-Float Positive-Float)
   (-> Nonnegative-Float Positive-Real Positive-Float)
   (-> Negative-Float Nonpositive-Real Negative-Float)
   (-> Nonpositive-Real Negative-Float Negative-Float)
   (-> Negative-Real Nonpositive-Float Negative-Float)
   (-> Nonpositive-Float Negative-Real Negative-Float)
   (-> Nonnegative-Float Nonnegative-Real Nonnegative-Float)
   (-> Nonnegative-Real Nonnegative-Float Nonnegative-Float)
   (-> Nonpositive-Float Nonpositive-Real Nonpositive-Float)
   (-> Nonpositive-Real Nonpositive-Float Nonpositive-Float)
   (-> Float Real Float)
   (-> Real Float Float)
   (-> Float Float Float)
   (-> Positive-Single-Float (union Nonnegative-Rational Nonnegative-Single-Float) Positive-Single-Float)
   (-> (union Nonnegative-Rational Nonnegative-Single-Float) Positive-Single-Float Positive-Single-Float)
   (-> (union Positive-Rational Positive-Single-Float) Nonnegative-Single-Float Positive-Single-Float)
   (-> Nonnegative-Single-Float (union Positive-Rational Positive-Single-Float) Positive-Single-Float)
   (-> Negative-Single-Float (union Nonpositive-Rational Nonpositive-Single-Float) Negative-Single-Float)
   (-> (union Nonpositive-Rational Nonpositive-Single-Float) Negative-Single-Float Negative-Single-Float)
   (-> (union Negative-Rational Negative-Single-Float) Nonpositive-Single-Float Negative-Single-Float)
   (-> Nonpositive-Single-Float (union Negative-Rational Negative-Single-Float) Negative-Single-Float)
   (-> Nonnegative-Single-Float (union Nonnegative-Rational Nonnegative-Single-Float) Nonnegative-Single-Float)
   (-> (union Nonnegative-Rational Nonnegative-Single-Float) Nonnegative-Single-Float Nonnegative-Single-Float)
   (-> Nonpositive-Single-Float (union Nonpositive-Rational Nonpositive-Single-Float) Nonpositive-Single-Float)
   (-> (union Nonpositive-Rational Nonpositive-Single-Float) Nonpositive-Single-Float Nonpositive-Single-Float)
   (-> Single-Float (union Rational Single-Float) Single-Float)
   (-> (union Rational Single-Float) Single-Float Single-Float)
   (-> Single-Float Single-Float Single-Float)
   (-> Positive-InexactReal Nonnegative-Real Positive-InexactReal)
   (-> Nonnegative-Real Positive-InexactReal Positive-InexactReal)
   (-> Positive-Real Nonnegative-InexactReal Positive-InexactReal)
   (-> Nonnegative-InexactReal Positive-Real Positive-InexactReal)
   (-> Negative-InexactReal Nonpositive-Real Negative-InexactReal)
   (-> Nonpositive-Real Negative-InexactReal Negative-InexactReal)
   (-> Negative-Real Nonpositive-InexactReal Negative-InexactReal)
   (-> Nonpositive-InexactReal Negative-Real Negative-InexactReal)
   (-> Nonnegative-InexactReal Nonnegative-Real Nonnegative-InexactReal)
   (-> Nonnegative-Real Nonnegative-InexactReal Nonnegative-InexactReal)
   (-> Nonpositive-InexactReal Nonpositive-Real Nonpositive-InexactReal)
   (-> Nonpositive-Real Nonpositive-InexactReal Nonpositive-InexactReal)
   (-> InexactReal Real InexactReal)
   (-> Real InexactReal InexactReal)
   (-> Positive-Real Nonnegative-Real Positive-Real)
   (-> Nonnegative-Real Positive-Real Positive-Real)
   (-> Negative-Real Nonpositive-Real Negative-Real)
   (-> Nonpositive-Real Negative-Real Negative-Real)
   (-> Nonnegative-Real Nonnegative-Real Nonnegative-Real)
   (-> Nonpositive-Real Nonpositive-Real Nonpositive-Real)
   (-> Real Real Real)
   (-> Exact-Number Exact-Number Exact-Number)
   (-> Float-Complex Number Float-Complex)
   (-> Number Float-Complex Float-Complex)
   (-> Float Inexact-Complex Float-Complex)
   (-> Inexact-Complex Float Float-Complex)
   (-> Single-Float-Complex (union Rational Single-Float Single-Float-Complex) Single-Float-Complex)
   (-> (union Rational Single-Float Single-Float-Complex) Single-Float-Complex Single-Float-Complex)
   (-> Inexact-Complex (union Rational InexactReal Inexact-Complex) Inexact-Complex)
   (-> (union Rational InexactReal Inexact-Complex) Inexact-Complex Inexact-Complex)
   ))

(define-funtype type-of-<
  (case->
   (-> (Integer Integer) (Bool tt tt))))
