#lang typed/racket/base

(require "syntactic-type-rep.rkt")

(provide type-of-add1
         type-of-+
         type-of-<)


(: type-of-add1 (Listof UNOP))
(define type-of-add1
  (list ;; 23 cases
   (UNOP Zero One)
   (UNOP One Positive-Byte)
   (UNOP Byte Positive-Index)
   (UNOP Index Positive-Fixnum)
   (UNOP Negative-Fixnum Nonpositive-Fixnum)
   (UNOP Nonpositive-Fixnum Fixnum)
   (UNOP Nonnegative-Integer Positive-Integer)
   (UNOP Negative-Integer Nonpositive-Integer)
   (UNOP Integer Integer)
   (UNOP Nonnegative-Rational Positive-Rational)
   (UNOP Rational Rational)
   (UNOP Nonnegative-Float Positive-Float)
   (UNOP Float Float)
   (UNOP Nonnegative-Single-Float Positive-Single-Float)
   (UNOP Single-Float Single-Float)
   (UNOP Nonnegative-Inexact-Real Positive-Inexact-Real)
   (UNOP Inexact-Real Inexact-Real)
   (UNOP Nonnegative-Real Positive-Real)
   (UNOP Real Real)
   (UNOP Float-Complex Float-Complex)
   (UNOP Single-Float-Complex Single-Float-Complex)
   (UNOP Inexact-Complex Inexact-Complex)
   (UNOP Number Number)))

(: type-of-+ (Listof BINOP))
(define type-of-+
  (list ;; 86 cases
   (BINOP Positive-Byte Positive-Byte Positive-Index)
   (BINOP Byte Byte Index)
   (BINOP Positive-Byte Positive-Byte Positive-Index)
   (BINOP Positive-Index Index Positive-Fixnum)
   (BINOP Index Positive-Index Positive-Fixnum)
   (BINOP Index Index Nonnegative-Fixnum)
   (BINOP Negative-Fixnum One Nonpositive-Fixnum)
   (BINOP One Negative-Fixnum Nonpositive-Fixnum)
   (BINOP Nonpositive-Fixnum Nonnegative-Fixnum Fixnum)
   (BINOP Nonnegative-Fixnum Nonpositive-Fixnum Fixnum)
   (BINOP Positive-Integer Nonnegative-Integer Positive-Integer)
   (BINOP Nonnegative-Integer Positive-Integer Positive-Integer)
   (BINOP Negative-Integer Nonpositive-Integer Negative-Integer)
   (BINOP Nonpositive-Integer Negative-Integer Negative-Integer)
   (BINOP Nonnegative-Integer Nonnegative-Integer Nonnegative-Integer)
   (BINOP Nonpositive-Integer Nonpositive-Integer Nonpositive-Integer)
   (BINOP Integer Integer Integer)
   (BINOP Positive-Rational Nonnegative-Rational Positive-Rational)
   (BINOP Nonnegative-Rational Positive-Rational Positive-Rational)
   (BINOP Negative-Rational Nonpositive-Rational Negative-Rational)
   (BINOP Nonpositive-Rational Negative-Rational Negative-Rational)
   (BINOP Nonnegative-Rational Nonnegative-Rational Nonnegative-Rational)
   (BINOP Nonpositive-Rational Nonpositive-Rational Nonpositive-Rational)
   (BINOP Rational Rational Rational)
   (BINOP Positive-Float Nonnegative-Real Positive-Float)
   (BINOP Nonnegative-Real Positive-Float Positive-Float)
   (BINOP Positive-Real Nonnegative-Float Positive-Float)
   (BINOP Nonnegative-Float Positive-Real Positive-Float)
   (BINOP Negative-Float Nonpositive-Real Negative-Float)
   (BINOP Nonpositive-Real Negative-Float Negative-Float)
   (BINOP Negative-Real Nonpositive-Float Negative-Float)
   (BINOP Nonpositive-Float Negative-Real Negative-Float)
   (BINOP Nonnegative-Float Nonnegative-Real Nonnegative-Float)
   (BINOP Nonnegative-Real Nonnegative-Float Nonnegative-Float)
   (BINOP Nonpositive-Float Nonpositive-Real Nonpositive-Float)
   (BINOP Nonpositive-Real Nonpositive-Float Nonpositive-Float)
   (BINOP Float Real Float)
   (BINOP Real Float Float)
   (BINOP Float Float Float)
   (BINOP Positive-Single-Float (Un Nonnegative-Rational Nonnegative-Single-Float) Positive-Single-Float)
   (BINOP (Un Nonnegative-Rational Nonnegative-Single-Float) Positive-Single-Float Positive-Single-Float)
   (BINOP (Un Positive-Rational Positive-Single-Float) Nonnegative-Single-Float Positive-Single-Float)
   (BINOP Nonnegative-Single-Float (Un Positive-Rational Positive-Single-Float) Positive-Single-Float)
   (BINOP Negative-Single-Float (Un Nonpositive-Rational Nonpositive-Single-Float) Negative-Single-Float)
   (BINOP (Un Nonpositive-Rational Nonpositive-Single-Float) Negative-Single-Float Negative-Single-Float)
   (BINOP (Un Negative-Rational Negative-Single-Float) Nonpositive-Single-Float Negative-Single-Float)
   (BINOP Nonpositive-Single-Float (Un Negative-Rational Negative-Single-Float) Negative-Single-Float)
   (BINOP Nonnegative-Single-Float (Un Nonnegative-Rational Nonnegative-Single-Float) Nonnegative-Single-Float)
   (BINOP (Un Nonnegative-Rational Nonnegative-Single-Float) Nonnegative-Single-Float Nonnegative-Single-Float)
   (BINOP Nonpositive-Single-Float (Un Nonpositive-Rational Nonpositive-Single-Float) Nonpositive-Single-Float)
   (BINOP (Un Nonpositive-Rational Nonpositive-Single-Float) Nonpositive-Single-Float Nonpositive-Single-Float)
   (BINOP Single-Float (Un Rational Single-Float) Single-Float)
   (BINOP (Un Rational Single-Float) Single-Float Single-Float)
   (BINOP Single-Float Single-Float Single-Float)
   (BINOP Positive-Inexact-Real Nonnegative-Real Positive-Inexact-Real)
   (BINOP Nonnegative-Real Positive-Inexact-Real Positive-Inexact-Real)
   (BINOP Positive-Real Nonnegative-Inexact-Real Positive-Inexact-Real)
   (BINOP Nonnegative-Inexact-Real Positive-Real Positive-Inexact-Real)
   (BINOP Negative-Inexact-Real Nonpositive-Real Negative-Inexact-Real)
   (BINOP Nonpositive-Real Negative-Inexact-Real Negative-Inexact-Real)
   (BINOP Negative-Real Nonpositive-Inexact-Real Negative-Inexact-Real)
   (BINOP Nonpositive-Inexact-Real Negative-Real Negative-Inexact-Real)
   (BINOP Nonnegative-Inexact-Real Nonnegative-Real Nonnegative-Inexact-Real)
   (BINOP Nonnegative-Real Nonnegative-Inexact-Real Nonnegative-Inexact-Real)
   (BINOP Nonpositive-Inexact-Real Nonpositive-Real Nonpositive-Inexact-Real)
   (BINOP Nonpositive-Real Nonpositive-Inexact-Real Nonpositive-Inexact-Real)
   (BINOP Inexact-Real Real Inexact-Real)
   (BINOP Real Inexact-Real Inexact-Real)
   (BINOP Positive-Real Nonnegative-Real Positive-Real)
   (BINOP Nonnegative-Real Positive-Real Positive-Real)
   (BINOP Negative-Real Nonpositive-Real Negative-Real)
   (BINOP Nonpositive-Real Negative-Real Negative-Real)
   (BINOP Nonnegative-Real Nonnegative-Real Nonnegative-Real)
   (BINOP Nonpositive-Real Nonpositive-Real Nonpositive-Real)
   (BINOP Real Real Real)
   (BINOP Exact-Number Exact-Number Exact-Number)
   (BINOP Float-Complex Number Float-Complex)
   (BINOP Number Float-Complex Float-Complex)
   (BINOP Float Inexact-Complex Float-Complex)
   (BINOP Inexact-Complex Float Float-Complex)
   (BINOP Single-Float-Complex (Un Rational Single-Float Single-Float-Complex) Single-Float-Complex)
   (BINOP (Un Rational Single-Float Single-Float-Complex) Single-Float-Complex Single-Float-Complex)
   (BINOP Inexact-Complex (Un Rational Inexact-Real Inexact-Complex) Inexact-Complex)
   (BINOP (Un Rational Inexact-Real Inexact-Complex) Inexact-Complex Inexact-Complex)
   (BINOP Number Number Number)))

(: type-of-< (Listof COMP))
(define type-of-<
  (list ;; 88 cases =O
   (COMP Integer One (∈ 0 Nonpositive-Integer) (∈ 0 Positive-Integer))
   (COMP Real Zero (∈ 0 Negative-Real) (∈ 0 Nonnegative-Real))
   (COMP Zero Real (∈ 1 Positive-Real) (∈ 1 Nonpositive-Real))
   (COMP Real Real-Zero (∈ 0 Negative-Real) tt) ;; False says nothing because of NaN
   (COMP Real-Zero Real (∈ 1 Positive-Real) tt) ;; False says nothing because of NaN
   (COMP Byte Positive-Byte tt (∈ 0 Positive-Byte))
   (COMP Byte Byte (∈ 1 Positive-Byte) tt)
   (COMP Positive-Integer Byte (∧ (∈ 0 Positive-Byte) (∈ 1 Positive-Byte)) tt)
   (COMP Positive-Real Byte (∈ 1 Positive-Byte) tt) ; Positive-Real is ok here, no prop for #f
   (COMP Byte Positive-Integer tt (∧ (∈ 0 Positive-Byte) (∈ 1 Positive-Byte)))
   (COMP Byte Positive-Rational tt (∈ 0 Positive-Byte)) ; can't be Positive-Real, which includes NaN
   (COMP Nonnegative-Integer Byte (∧ (∈ 0 Byte) (∈ 1 Positive-Byte)) tt)
   (COMP Nonnegative-Real Byte (∈ 1 Positive-Byte) tt)
   (COMP Byte Nonnegative-Integer tt (∈ 1 Byte))
   (COMP Index Positive-Index tt (∈ 0 Positive-Index))
   (COMP Index Index (∈ 1 Positive-Index) tt)
   (COMP Positive-Integer Index (∧ (∈ 0 Positive-Index) (∈ 1 Positive-Index)) tt)
   (COMP Positive-Real Index (∈ 1 Positive-Index) tt)
   (COMP Index Positive-Integer tt (∧ (∈ 0 Positive-Index) (∈ 1 Positive-Index)))
   (COMP Index Positive-Rational tt (∈ 0 Positive-Index)) ; can't be Positive-Real, which includes NaN
   (COMP Nonnegative-Integer Index (∧ (∈ 0 Index) (∈ 1 Positive-Index)) tt)
   (COMP Nonnegative-Real Index (∈ 1 Positive-Index) tt)
   (COMP Index Nonnegative-Integer tt (∈ 1 Index))
   (COMP Fixnum Positive-Integer tt (∧ (∈ 0 Positive-Fixnum) (∈ 1 Positive-Fixnum)))
   (COMP Fixnum Positive-Rational tt (∈ 0 Positive-Fixnum))
   (COMP Fixnum Nonnegative-Integer tt (∧ (∈ 0 Nonnegative-Fixnum) (∈ 1 Nonnegative-Fixnum)))
   (COMP Fixnum Nonnegative-Rational tt (∈ 0 Nonnegative-Fixnum))
   (COMP Nonnegative-Integer Fixnum (∧ (∈ 0 Nonnegative-Fixnum) (∈ 1 Positive-Fixnum)) tt)
   (COMP Nonnegative-Real Fixnum (∈ 1 Positive-Fixnum) tt)
   (COMP Fixnum Nonpositive-Integer (∧ (∈ 0 Negative-Fixnum) (∈ 1 Nonpositive-Fixnum)) tt)
   (COMP Fixnum Nonpositive-Real (∈ 0 Negative-Fixnum) tt)
   (COMP Negative-Integer Fixnum tt (∧ (∈ 0 Negative-Fixnum) (∈ 1 Negative-Fixnum)))
   (COMP Negative-Rational Fixnum tt (∈ 1 Negative-Fixnum))
   (COMP Nonpositive-Integer Fixnum tt (∧ (∈ 0 Nonpositive-Fixnum) (∈ 1 Nonpositive-Fixnum)))
   (COMP Nonpositive-Rational Fixnum tt (∈ 1 Nonpositive-Fixnum))
   (COMP Real Positive-Infinity
         (∉ 0 (Un Inexact-Real-NaN Positive-Infinity))
         (∈ 0 (Un Inexact-Real-NaN Positive-Infinity)))
   (COMP Negative-Infinity Real
         (∉ 1 (Un Inexact-Real-NaN Negative-Infinity))
         (∈ 1 (Un Inexact-Real-NaN Negative-Infinity)))
   (COMP Positive-Infinity Real ff tt)
   (COMP Real Negative-Infinity ff tt)
   ;; <-type-pattern Integer
   (COMP Integer Zero (∈ 0 Negative-Integer) (∈ 0 Nonnegative-Integer))
   (COMP Zero Integer (∈ 1 Positive-Integer) (∈ 1 Nonpositive-Integer))
   (COMP Integer Positive-Real tt (∈ 0 Positive-Integer))
   (COMP Integer Nonnegative-Real tt (∈ 0 Nonnegative-Integer))
   (COMP Nonnegative-Real Integer (∈ 1 Positive-Integer) tt)
   (COMP Integer Nonpositive-Real (∈ 0 Negative-Integer) tt)
   (COMP Negative-Real Integer tt (∈ 1 Negative-Integer))
   (COMP Nonpositive-Real Integer tt (∈ 1 Nonpositive-Integer))
   ;; <-type-pattern Rational
   (COMP Rational Zero (∈ 0 Negative-Rational) (∈ 0 Nonnegative-Rational))
   (COMP Zero Rational (∈ 1 Positive-Rational) (∈ 1 Nonpositive-Rational))
   (COMP Rational Positive-Real tt (∈ 0 Positive-Rational))
   (COMP Rational Nonnegative-Real tt (∈ 0 Nonnegative-Rational))
   (COMP Nonnegative-Real Rational (∈ 1 Positive-Rational) tt)
   (COMP Rational Nonpositive-Real (∈ 0 Negative-Rational) tt)
   (COMP Negative-Real Rational tt (∈ 1 Negative-Rational))
   (COMP Nonpositive-Real Rational tt (∈ 1 Nonpositive-Rational))
   ;; <-type-pattern Float
   (COMP Float Real-Zero (∈ 0 Negative-Float) tt)
   (COMP Real-Zero Float (∈ 1 Positive-Float) tt)
   (COMP Float Positive-Real tt tt)
   (COMP Float Nonnegative-Real tt tt)
   (COMP Nonnegative-Real Float (∈ 1 Positive-Float) tt)
   (COMP Float Nonpositive-Real (∈ 0 Negative-Float) tt)
   (COMP Negative-Real Float tt tt)
   (COMP Nonpositive-Real Float tt tt)
   ;; <-type-pattern Single-Float
   (COMP Single-Float Real-Zero (∈ 0 Negative-Single-Float) tt)
   (COMP Real-Zero Single-Float (∈ 1 Positive-Single-Float) tt)
   (COMP Single-Float Positive-Real tt tt)
   (COMP Single-Float Nonnegative-Real tt tt)
   (COMP Nonnegative-Real Single-Float (∈ 1 Positive-Single-Float) tt)
   (COMP Single-Float Nonpositive-Real (∈ 0 Negative-Single-Float) tt)
   (COMP Negative-Real Single-Float tt tt)
   (COMP Nonpositive-Real Single-Float tt tt)
   ;; <-type-pattern Inexact-Real
   (COMP Inexact-Real Real-Zero (∈ 0 Negative-Inexact-Real) tt)
   (COMP Real-Zero Inexact-Real (∈ 1 Positive-Inexact-Real) tt)
   (COMP Inexact-Real Positive-Real tt tt)
   (COMP Inexact-Real Nonnegative-Real tt tt)
   (COMP Nonnegative-Real Inexact-Real (∈ 1 Positive-Inexact-Real) tt)
   (COMP Inexact-Real Nonpositive-Real (∈ 0 Negative-Inexact-Real) tt)
   (COMP Negative-Real Inexact-Real tt tt)
   (COMP Nonpositive-Real Inexact-Real tt tt)
   ;; <-type-pattern Real
   (COMP Real Real-Zero (∈ 0 Negative-Real) tt)
   (COMP Real-Zero Real (∈ 1 Positive-Real) tt)
   (COMP Real Positive-Real tt tt)
   (COMP Real Nonnegative-Real tt tt)
   (COMP Nonnegative-Real Real (∈ 1 Positive-Real) tt)
   (COMP Real Nonpositive-Real (∈ 0 Negative-Real) tt)
   (COMP Negative-Real Real tt tt)
   (COMP Nonpositive-Real Real tt tt)
   ;; end of <-type-pattern
   (COMP Real Real tt tt)))


;(define (<-type-pattern base pos non-neg neg non-pos [zero (term Real-Zero)]
;                        #:no-false-props? [no-false-props? #f])
;  (define (<-case l r true-prop false-prop)
;    (term (-> ,base ,zero Boolean : ,true-prop ,(if no-false-props? (term tt) false-prop))))
;  (list (<-case base zero (term (∈ 0 ,neg)) (term (∈ 0 ,non-neg)))
;        (<-case zero base (term (∈ 1 ,pos)) (term (∈ 1 ,non-pos)))
;        (<-case base (term Positive-Real) (term tt) (term (∈ 0 ,pos)))
;        (<-case base (term Nonnegative-Real) (term tt) (term (∈ 0 ,non-neg)))
;        (<-case (term Nonnegative-Real) base (term (∈ 1 ,pos)) 'tt)
;        (<-case base (term Nonpositive-Real) (term (∈ 0 ,neg)) 'tt)
;        (<-case (term Negative-Real) base (term tt) (term (∈ 1 ,neg)))
;        (<-case (term Nonpositive-Real) base (term tt) (term (∈ 1 ,non-pos)))))
;
;(<-type-pattern (term Integer)
;                (term Positive-Integer)
;                (term Nonnegative-Integer)
;                (term Negative-Integer)
;                (term Nonpositive-Integer)
;                (term Zero))
;(<-type-pattern (term Rational)
;                (term Positive-Rational)
;                (term Nonnegative-Rational)
;                (term Negative-Rational)
;                (term Nonpositive-Rational)
;                (term Zero))
;(<-type-pattern (term Float)
;                (term Positive-Float)
;                (term Nonnegative-Float)
;                (term Negative-Float)
;                (term Nonpositive-Float)
;                #:no-false-props? #t)
;(<-type-pattern (term Single-Float)
;                (term Positive-Single-Float)
;                (term Nonnegative-Single-Float)
;                (term Negative-Single-Float)
;                (term Nonpositive-Single-Float)
;                #:no-false-props? #t)
;(<-type-pattern (term Inexact-Real)
;                (term Positive-Inexact-Real)
;                (term Nonnegative-Inexact-Real)
;                (term Negative-Inexact-Real)
;                (term Nonpositive-Inexact-Real)
;                #:no-false-props? #t)
;(<-type-pattern (term Real)
;                (term Positive-Real)
;                (term Nonnegative-Real)
;                (term Negative-Real)
;                (term Nonpositive-Real)
;                #:no-false-props? #t)

