module Types.SyntacticOpTypes where

import Types.LazyBDD
import Types.BaseEnv


opTypes :: [(String, OpSpec)]
opTypes =
  [ ("add1", (UnOp
              [ (zero, one)
              , (one, posByte)
              , (byte, posIndex)
              , (index, posFixnum)
              , (negFixnum, nonposFixnum)
              , (nonposFixnum, fixnum)
              , (nonnegInteger, posInteger)
              , (negInteger, nonposInteger)
              , (integer, integer)
              , (nonnegRational, posRational)
              , (rational, rational)
              , (nonnegFloat, posFloat)
              , (float, float)
              , (nonnegSingleFloat, posSingleFloat)
              , (singleFloat, singleFloat)
              , (nonnegInexactReal, posInexactReal)
              , (inexactReal, inexactReal)
              , (nonnegReal, posReal)
              , (real, real)
              , (floatComplex, floatComplex)
              , (singleFloatComplex, singleFloatComplex)
              , (inexactComplex, inexactComplex)
              , (number, number)]))
    
  , ("sub1", (UnOp
              [ (one, zero)
              , (posByte, byte)
              , (posIndex, index)
              , (index, fixnum)
              , (posFixnum, nonnegFixnum)
              , (nonnegFixnum, fixnum)
              , (posInteger, nonnegInteger)
              , (nonposInteger, negInteger)
              , (integer, integer)
              , (nonposRational, negRational)
              , (rational, rational)
              , (nonposFloat, negFloat)
              , (float, float)
              , (nonposSingleFloat, negSingleFloat)
              , (singleFloat, singleFloat)
              , (nonposInexactReal, negInexactReal)
              , (inexactReal, inexactReal)
              , (nonposReal, negReal)
              , (real, real)
              , (floatComplex, floatComplex)
              , (singleFloatComplex, singleFloatComplex)
              , (inexactComplex, inexactComplex)
              , (number, number)]))
    
    --abs is not the identity on neg zeros.
  , ("abs", (UnOp
             [ (zero, zero)
             , (posReal, posReal)
             , (floatZero, floatZero) -- we know we at least get *some* zero, and that it preserves exactness
             , (singleFloatZero, singleFloatZero)
             , (realZero, realZero)
             , ((tyOr' [posInteger, negInteger]), posInteger) -- abs not be closed on fixnums
             , (integer, nonnegInteger)
             , ((tyOr' [posRational, negRational]), posRational)
             , (rational, nonnegRational)
             , ((tyOr' [posFloat, negFloat]), posFloat)
             , (float, nonnegFloat)
             , ((tyOr' [posSingleFloat, negSingleFloat]), posSingleFloat)
             , (singleFloat, nonnegSingleFloat)
             , ((tyOr' [posInexactReal, negInexactReal]), posInexactReal)
             , (inexactReal, nonnegInexactReal)
             , ((tyOr' [posReal, negReal]), posReal)
             , (real, nonnegReal)]))

  , ("sqr", (UnOp [ (zero, zero)
                  , (one, one)
                  , (posByte, posIndex)
                  , (byte, index)
                  , (posInteger, posInteger)
                  , (integer, nonnegInteger)
                  , (posRational, posRational)
                  , (rational, nonnegRational)
                  , (float, nonnegFloat)
                  , (singleFloat, nonnegSingleFloat)
                  , (inexactReal, nonnegInexactReal)
                  , (real, nonnegReal)
                  , (floatComplex, floatComplex)
                  , (singleFloatComplex, singleFloatComplex)
                  , (inexactComplex, inexactComplex)
                  , (exactNumber, exactNumber)
                  , (number, number)]))
    
  , ("sqrt", (UnOp [(zero, zero)
                   , (one, one)
                   , (floatPosZero, floatPosZero)
                   , (floatNegZero, floatNegZero)
                   , (floatZero, floatZero)
                   , (posFloat, posFloat)
                   , (nonnegFloat, nonnegFloat)
                   , (singleFloatPosZero, singleFloatPosZero)
                   , (singleFloatNegZero, singleFloatNegZero)
                   , (singleFloatZero, singleFloatZero)
                   , (posSingleFloat, posSingleFloat)
                   , (nonnegSingleFloat, nonnegSingleFloat)
                   , (inexactRealPosZero, inexactRealPosZero)
                   , (inexactRealNegZero, inexactRealNegZero)
                   , (inexactRealZero, inexactRealZero)
                   , (posInexactReal, posInexactReal)
                   , (nonnegInexactReal, nonnegInexactReal)
                   , (realZero, realZero)
                   , (posReal, posReal)
                   , (nonnegReal, nonnegReal)
                   , (floatComplex, floatComplex)
                   , (singleFloatComplex, singleFloatComplex)
                   , (inexactComplex, inexactComplex)
                   , (number, number)]))

  , ("real->double-flonum", (UnOp [ (floatPosZero, floatPosZero)
                                  , (floatNegZero, floatNegZero)
                                  , (floatZero, floatZero)
                                  , (floatNan, floatNan)
                                  , (posFloat, posFloat)
                                  , (nonnegFloat, nonnegFloat)
                                  , (negFloat, negFloat)
                                  , (nonposFloat, nonposFloat)
                                  , (float, float)
                                  , (singleFloatPosZero, floatPosZero)
                                  , (singleFloatNegZero, floatNegZero)
                                  , (realZero, floatZero)
                                  , (posInteger, posFloat)
                                  , (negInteger, negFloat)
                                  , (nonnegReal, nonnegFloat)
                                  , (nonposReal, nonposFloat)
                                  , (real, float)]))

  , ("real->single-flonum" , (UnOp [ (singleFloatPosZero, singleFloatPosZero)
                                   , (singleFloatNegZero, singleFloatNegZero)
                                   , (singleFloatZero, singleFloatZero)
                                   , (singleFloatNan, singleFloatNan)
                                   , (posSingleFloat, posSingleFloat)
                                   , (nonnegSingleFloat, nonnegSingleFloat)
                                   , (negSingleFloat, negSingleFloat)
                                   , (nonposSingleFloat, nonposSingleFloat)
                                   , (singleFloat, singleFloat)
                                   , (floatPosZero, singleFloatPosZero)
                                   , (floatNegZero, singleFloatNegZero)
                                   , (realZero, singleFloatZero)
                                   , (posInteger, posSingleFloat)
                                   , (negInteger, negSingleFloat)
                                   , (nonnegReal, nonnegSingleFloat)
                                   , (nonposReal, nonposSingleFloat)
                                   , (real, singleFloatZero)]))

  , ("inexact->exact" , (UnOp [ (zero, zero)
                              , (one, one)
                              , (posByte, posByte)
                              , (byte, byte)
                              , (posIndex, posIndex)
                              , (index, index)
                              , (posFixnum, posFixnum)
                              , (nonnegFixnum, nonnegFixnum)
                              , (negFixnum, negFixnum)
                              , (nonposFixnum, nonposFixnum)
                              , (fixnum, fixnum)
                              , (posInteger, posInteger)
                              , (nonnegInteger, nonnegInteger)
                              , (negInteger, negInteger)
                              , (nonposInteger, nonposInteger)
                              , (integer, integer)
                              , (posExactRational, posExactRational)
                              , (nonnegExactRational, nonnegExactRational)
                              , (negExactRational, negExactRational)
                              , (nonposExactRational, nonposExactRational)
                              , (exactRational, exactRational)
                              , (realZero, zero)
                              , (posReal, posExactRational)
                              , (nonnegReal, nonnegExactRational)
                              , (negReal, negExactRational)
                              , (nonposReal, nonposExactRational)
                              , (real, exactRational)
                              , (number, exactNumber)]))

  , ("expt", (BinOp [ (one, rational, one)
                    , (number, zero, one) -- will error if neg
                    , (posInteger, nonnegInteger, posInteger)
                    , (nonnegInteger, nonnegInteger, nonnegInteger)
                    , (integer, nonnegInteger, integer)
                    , (posInteger, integer, posRational)
                    , (nonnegInteger, integer, nonnegRational)
                    , (integer, integer, rational)
                    , (posRational, integer, posRational)
                    , (nonnegRational, integer, nonnegRational)
                    , (rational, integer, rational)
                    , (nonnegFloat, float, nonnegFloat)
                    , (nonnegFloat, real, (tyOr nonnegFloat one))
                    , (posReal, nonnegFloat, (tyOr nonnegFloat one))
                    , (float, (tyOr negFixnum posFixnum), float)
                    , (float, fixnum, (tyOr float one))
                    , (float, float, (tyOr float floatComplex))
                    , (posSingleFloat, (tyOr' [singleFloat, negFixnum, posFixnum]), nonnegSingleFloat)
                    , (nonnegSingleFloat, (tyOr' [singleFloat, negFixnum, posFixnum]), singleFloat)
                    , (singleFloat, (tyOr negFixnum posFixnum), singleFloat)
                    , (singleFloat, fixnum, (tyOr singleFloat one))
                    , (singleFloat, singleFloat, (tyOr singleFloat singleFloatComplex))
                    , (posInexactReal, (tyOr negFixnum posFixnum), nonnegInexactReal)
                    , (nonnegInexactReal, (tyOr negFixnum posFixnum), inexactReal)
                    , (posReal, real, nonnegReal)
                    , (nonnegReal, real, real)
                    , (inexactReal, (tyOr negFixnum posFixnum), inexactReal)
                    , (inexactReal, inexactReal, (tyOr inexactReal inexactComplex))
                    , (real, nonnegInteger, real)
                    , (floatComplex, floatComplex, floatComplex)
                    , (floatComplex, float, (tyOr floatComplex float))
                    , (floatComplex, inexactReal, (tyOr floatComplex inexactReal))
                    , (floatComplex, inexactComplex, floatComplex)
                    , (singleFloatComplex, singleFloatComplex, singleFloatComplex)
                    , (singleFloatComplex, singleFloat, (tyOr singleFloatComplex singleFloat))
                    , (inexactComplex, inexactComplex, inexactComplex)
                    , (number, number, number)]))
  
  , ("modulo", (BinOp [ (one, one, zero)
                      , (integer, byte, byte)
                      , (byte, nonnegInteger, byte)
                      , (integer, index, index)
                      , (index, nonnegInteger, index)
                      , (integer, nonnegFixnum, nonnegFixnum)
                      , (nonnegFixnum, nonnegInteger, nonnegFixnum)
                      , (integer, nonnegInteger, nonnegInteger)
                      , (nonnegInteger, nonnegInteger, nonnegInteger)
                      , (integer, nonposFixnum, nonposFixnum)
                      , (integer, nonposInteger, nonposInteger)
                      , (integer, fixnum, fixnum)
                      , (integer, integer, integer)]))
  
  , ("quotient", (BinOp [ (zero, integer, zero)
                        , (posByte, one, posByte)
                        , (byte, one, byte)
                        , (posIndex, one, posIndex)
                        , (index, one, index)
                        , (posFixnum, one, posFixnum)
                        , (nonnegFixnum, one, nonnegFixnum)
                        , (negFixnum, one, negFixnum)
                        , (nonposFixnum, one, nonposFixnum)
                        , (fixnum, one, fixnum)
                        , (byte, nonnegInteger, byte)
                        , (byte, integer, fixnum)
                        , (index, nonnegInteger, index)
                        , (index, integer, fixnum)
                        , (nonnegFixnum, nonposFixnum, nonposFixnum)
                        , (nonposFixnum, nonnegFixnum, nonposFixnum)
                        , (nonposFixnum, nonposFixnum, nonnegInteger)
                        , (nonnegFixnum, nonnegInteger, nonnegFixnum)
                        , (nonnegFixnum, integer, fixnum)
                        , (nonnegInteger, nonnegInteger, nonnegInteger)
                        , (nonnegInteger, nonposInteger, nonposInteger)
                        , (nonposInteger, nonnegInteger, nonposInteger)
                        , (nonposInteger, nonposInteger, nonnegInteger)
                        , (integer, integer, integer)]))

  , ("+", (BinOp
            [ (posByte, posByte, posIndex)
            , (byte, byte, index)
            , (posByte, posByte, posIndex)
            , (posIndex, index, posFixnum)
            , (index, posIndex, posFixnum)
            , (index, index, nonnegFixnum)
            , (negFixnum, one, nonposFixnum)
            , (one, negFixnum, nonposFixnum)
            , (nonposFixnum, nonnegFixnum, fixnum)
            , (nonnegFixnum, nonposFixnum, fixnum)
            , (posInteger, nonnegInteger, posInteger)
            , (nonnegInteger, posInteger, posInteger)
            , (negInteger, nonposInteger, negInteger)
            , (nonposInteger, negInteger, negInteger)
            , (nonnegInteger, nonnegInteger, nonnegInteger)
            , (nonposInteger, nonposInteger, nonposInteger)
            , (integer, integer, integer)
            , (posRational, nonnegRational, posRational)
            , (nonnegRational, posRational, posRational)
            , (negRational, nonposRational, negRational)
            , (nonposRational, negRational, negRational)
            , (nonnegRational, nonnegRational, nonnegRational)
            , (nonposRational, nonposRational, nonposRational)
            , (rational, rational, rational)
            , (posFloat, nonnegReal, posFloat)
            , (nonnegReal, posFloat, posFloat)
            , (posReal, nonnegFloat, posFloat)
            , (nonnegFloat, posReal, posFloat)
            , (negFloat, nonposReal, negFloat)
            , (nonposReal, negFloat, negFloat)
            , (negReal, nonposFloat, negFloat)
            , (nonposFloat, negReal, negFloat)
            , (nonnegFloat, nonnegReal, nonnegFloat)
            , (nonnegReal, nonnegFloat, nonnegFloat)
            , (nonposFloat, nonposReal, nonposFloat)
            , (nonposReal, nonposFloat, nonposFloat)
            , (float, real, float)
            , (real, float, float)
            , (float, float, float)
            , (posSingleFloat, (tyOr' [nonnegRational, nonnegSingleFloat]), posSingleFloat)
            , ((tyOr' [nonnegRational, nonnegSingleFloat]), posSingleFloat, posSingleFloat)
            , ((tyOr' [posRational, posSingleFloat]), nonnegSingleFloat, posSingleFloat)
            , (nonnegSingleFloat, (tyOr' [posRational, posSingleFloat]), posSingleFloat)
            , (negSingleFloat, (tyOr' [nonposRational, nonposSingleFloat]), negSingleFloat)
            , ((tyOr' [nonposRational, nonposSingleFloat]), negSingleFloat, negSingleFloat)
            , ((tyOr' [negRational, negSingleFloat]), nonposSingleFloat, negSingleFloat)
            , (nonposSingleFloat, (tyOr' [negRational, negSingleFloat]), negSingleFloat)
            , (nonnegSingleFloat, (tyOr' [nonnegRational, nonnegSingleFloat]), nonnegSingleFloat)
            , ((tyOr' [nonnegRational, nonnegSingleFloat]), nonnegSingleFloat, nonnegSingleFloat)
            , (nonposSingleFloat, (tyOr' [nonposRational, nonposSingleFloat]), nonposSingleFloat)
            , ((tyOr' [nonposRational, nonposSingleFloat]), nonposSingleFloat, nonposSingleFloat)
            , (singleFloat, (tyOr' [rational, singleFloat]), singleFloat)
            , ((tyOr' [rational, singleFloat]), singleFloat, singleFloat)
            , (singleFloat, singleFloat, singleFloat)
            , (posInexactReal, nonnegReal, posInexactReal)
            , (nonnegReal, posInexactReal, posInexactReal)
            , (posReal, nonnegInexactReal, posInexactReal)
            , (nonnegInexactReal, posReal, posInexactReal)
            , (negInexactReal, nonposReal, negInexactReal)
            , (nonposReal, negInexactReal, negInexactReal)
            , (negReal, nonposInexactReal, negInexactReal)
            , (nonposInexactReal, negReal, negInexactReal)
            , (nonnegInexactReal, nonnegReal, nonnegInexactReal)
            , (nonnegReal, nonnegInexactReal, nonnegInexactReal)
            , (nonposInexactReal, nonposReal, nonposInexactReal)
            , (nonposReal, nonposInexactReal, nonposInexactReal)
            , (inexactReal, real, inexactReal)
            , (real, inexactReal, inexactReal)
            , (posReal, nonnegReal, posReal)
            , (nonnegReal, posReal, posReal)
            , (negReal, nonposReal, negReal)
            , (nonposReal, negReal, negReal)
            , (nonnegReal, nonnegReal, nonnegReal)
            , (nonposReal, nonposReal, nonposReal)
            , (real, real, real)
            , (exactNumber, exactNumber, exactNumber)
            , (floatComplex, number, floatComplex)
            , (number, floatComplex, floatComplex)
            , (float, inexactComplex, floatComplex)
            , (inexactComplex, float, floatComplex)
            , (singleFloatComplex, (tyOr' [rational, singleFloat, singleFloatComplex]), singleFloatComplex)
            , ((tyOr' [rational, singleFloat, singleFloatComplex]), singleFloatComplex, singleFloatComplex)
            , (inexactComplex, (tyOr' [rational, inexactReal, inexactComplex]), inexactComplex)
            , ((tyOr' [rational, inexactReal, inexactComplex]), inexactComplex, inexactComplex)
            , (number, number, number)]))

  , ("-", (BinOp
            [ (zero, zero, zero)
            , (zero, posFixnum, negFixnum) -- half negation pattern
            , (zero, nonnegFixnum, nonposFixnum) -- half negation pattern
            , (zero, posInteger, negInteger) -- negation pattern
            , (zero, nonnegInteger, nonposInteger) -- negation pattern
            , (zero, negInteger, posInteger) -- negation pattern
            , (zero, nonposInteger, nonnegInteger) -- negation pattern
            , (zero, posRational, negRational) -- negation pattern
            , (zero, nonnegRational, nonposRational) -- negation pattern
            , (zero, negRational, posRational) -- negation pattern
            , (zero, nonposRational, nonnegRational) -- negation pattern
            , (zero, posFloat, negFloat) -- negation pattern
            , (zero, nonnegFloat, nonposFloat) -- negation pattern
            , (zero, negFloat, posFloat) -- negation pattern
            , (zero, nonposFloat, nonnegFloat) -- negation pattern
            , (zero, posSingleFloat, negSingleFloat) -- negation pattern
            , (zero, nonnegSingleFloat, nonposSingleFloat) -- negation pattern
            , (zero, negSingleFloat, posSingleFloat) -- negation pattern
            , (zero, nonposSingleFloat, nonnegSingleFloat) -- negation pattern
            , (zero, posInexactReal, negInexactReal) -- negation pattern
            , (zero, nonnegInexactReal, nonposInexactReal) -- negation pattern
            , (zero, negInexactReal, posInexactReal) -- negation pattern
            , (zero, nonposInexactReal, nonnegInexactReal) -- negation pattern
            , (zero, posReal, negReal) -- negation pattern
            , (zero, nonnegReal, nonposReal) -- negation pattern
            , (zero, negReal, posReal) -- negation pattern
            , (zero, nonposReal, nonnegReal) -- negation pattern
            , (one, one, zero)
            , (posByte, one, byte)
            , (posIndex, one, index)
            , (posFixnum, one, nonnegFixnum)
            , (posInteger, one, nonnegInteger)
            , (nonnegFixnum, nonnegFixnum, fixnum)
            , (negFixnum, nonposFixnum, fixnum)
            , (posInteger, nonposInteger, posInteger)
            , (nonnegInteger, nonposInteger, nonnegInteger)
            , (negInteger, nonnegInteger, negInteger)
            , (nonposInteger, nonnegInteger, nonposInteger)
            , (integer, integer, integer)
            , (posRational, nonposRational, posRational)
            , (nonnegRational, nonposRational, nonnegRational)
            , (negRational, nonnegRational, negRational)
            , (nonposRational, nonnegRational, nonposRational)
            , (rational, rational, rational)
            , (float, float, float)
            , (float, real, float)
            , (real, float, float)
            , (singleFloat, singleFloat, singleFloat)
            , (singleFloat, (tyOr' [singleFloat, rational]), singleFloat)
            , ((tyOr' [singleFloat, rational]), singleFloat, singleFloat)
            , (inexactReal, inexactReal, inexactReal)
            , (inexactReal, (tyOr' [inexactReal, rational]), inexactReal)
            , ((tyOr' [inexactReal, rational]), inexactReal, inexactReal)
            , (real, real, real)
            , (exactNumber, exactNumber, exactNumber)
            , (floatComplex, floatComplex, floatComplex)
            , (floatComplex, number, floatComplex)
            , (number, floatComplex, floatComplex)
            , (singleFloatComplex, singleFloatComplex, singleFloatComplex)
            , (singleFloatComplex, (tyOr' [singleFloatComplex, exactNumber]), singleFloatComplex)
            , ((tyOr' [singleFloatComplex, exactNumber]), singleFloatComplex, singleFloatComplex)
            , (inexactComplex, inexactComplex, inexactComplex)
            , (inexactComplex, (tyOr' [inexactComplex, exactNumber]), inexactComplex)
            , ((tyOr' [inexactComplex, exactNumber]), inexactComplex, inexactComplex)
            , (number, number, number)]))

  , ("*", (BinOp
            [ (zero, number, zero)
            , (number, zero, zero)
            , (posByte, posByte, posIndex)
            , (byte, byte, index)
            , (posInteger, posInteger, posInteger)
            , (nonnegInteger, nonnegInteger, nonnegInteger)
            , (negInteger, negInteger, posInteger)
            , (negInteger, posInteger, negInteger)
            , (posInteger, negInteger, negInteger)
            , (nonposInteger, nonposInteger, nonnegInteger)
            , (nonposInteger, nonnegInteger, nonposInteger)
            , (nonnegInteger, nonposInteger, nonposInteger)
            , (integer, integer, integer)
            , (posRational, posRational, posRational)
            , (nonnegRational, nonnegRational, nonnegRational)
            , (negRational, negRational, posRational)
            , (negRational, posRational, negRational)
            , (posRational, negRational, negRational)
            , (nonposRational, nonposRational, nonnegRational)
            , (nonposRational, nonnegRational, nonposRational)
            , (nonnegRational, nonposRational, nonposRational)
            , (rational, rational, rational)
            , (floatZero, floatZero, floatZero)
            , (nonnegFloat, nonnegFloat, nonnegFloat) -- ; no pos * -> pos (underflow)
            , (negFloat, negFloat, nonnegFloat) -- possible underflow, so no neg neg -> pos
            , (nonnegFloat, posReal, nonnegFloat) -- ; real args don't include 0
            , (posReal, nonnegFloat, nonnegFloat)
            , (float, (tyOr' [posReal, negReal]), float)
            , ((tyOr' [posReal, negReal]), float, float)
            , (float, float, float)
            , (singleFloatZero, singleFloatZero, singleFloatZero)
            , (nonnegSingleFloat, nonnegSingleFloat, nonnegSingleFloat)
            , (negSingleFloat, negSingleFloat, nonnegSingleFloat) -- ; possible underflow, so no neg neg -> pos
            , (nonnegSingleFloat, (tyOr' [posRational, nonnegSingleFloat]), nonnegSingleFloat)
            , ((tyOr' [posRational, nonnegSingleFloat]), nonnegSingleFloat, nonnegSingleFloat)
            , (singleFloat, (tyOr' [posRational, negRational, singleFloat]), singleFloat)
            , ((tyOr' [posRational, negRational, singleFloat]), singleFloat, singleFloat)
            , (singleFloat, singleFloat, singleFloat)
            , (inexactRealZero, inexactRealZero, inexactRealZero)
            , (nonnegInexactReal, nonnegInexactReal, nonnegInexactReal)
            , (negInexactReal, negInexactReal, nonnegInexactReal)
            , (nonnegInexactReal, (tyOr' [posRational, nonnegInexactReal]), nonnegInexactReal)
            , ((tyOr' [posRational, nonnegInexactReal]), nonnegInexactReal, nonnegInexactReal)
            , (inexactReal, (tyOr' [posRational, negRational, inexactReal]), inexactReal)
            , ((tyOr' [posRational, negRational, inexactReal]), inexactReal, inexactReal)
            , (inexactReal, inexactReal, inexactReal)
            , (nonnegReal, nonnegReal, nonnegReal) -- (* +inf.0 0.0) -> +nan.0
            , (nonposReal, nonposReal, nonnegReal)
            , (nonposReal, nonnegReal, nonposReal)
            , (nonnegReal, nonposReal, nonposReal)
            , (real, real, real)
            , (floatComplex, (tyOr' [inexactComplex, inexactReal, posRational, negRational]), floatComplex)
            , ((tyOr' [inexactComplex, inexactReal, posRational, negRational]), floatComplex, floatComplex)
            , (singleFloatComplex, (tyOr' [singleFloatComplex, singleFloat, posRational, negRational]), singleFloatComplex)
            , ((tyOr' [singleFloatComplex, singleFloat, posRational, negRational]), singleFloatComplex, singleFloatComplex)
            , (inexactComplex, (tyOr' [inexactComplex, inexactReal, posRational, negRational]), inexactComplex)
            , ((tyOr' [inexactComplex, inexactReal, posRational, negRational]), inexactComplex, inexactComplex)
            , (number, number, number)]))

  , ("/", (BinOp
            [ (number, zero, emptyTy)
            , (zero, number, zero)
            , (one, one, one)
            , (posRational, posRational, posRational)
            , (nonnegRational, nonnegRational, nonnegRational)
            , (negRational, negRational, posRational)
            , (negRational, posRational, negRational)
            , (posRational, negRational, negRational)
            , (nonposRational, nonposRational, nonnegRational)
            , (nonposRational, nonnegRational, nonposRational)
            , (nonnegRational, nonposRational, nonposRational)
            , (rational, rational, rational)
            , (negFloat, negFloat, nonnegFloat)
            , (posFloat, posReal, nonnegFloat)
            , (posReal, posFloat, nonnegFloat)
            , ((tyOr' [posReal, negReal, float]), float, float)
            , (float, real, float) -- if any argument after the first is exact 0, not a problem
            , (float, float, float)
            , (negSingleFloat, negSingleFloat, nonnegSingleFloat) -- possible underflow, so no neg neg -> pos
            , (posSingleFloat, (tyOr' [posRational, posSingleFloat]), nonnegSingleFloat)
            , ((tyOr' [posRational, posSingleFloat]), posSingleFloat, nonnegSingleFloat)
            , (singleFloat, (tyOr' [posRational, negRational, singleFloat]), singleFloat)
            , ((tyOr' [posRational, negRational, singleFloat]), singleFloat, singleFloat)
            , (singleFloat, singleFloat, singleFloat)
            , (negInexactReal, negInexactReal, nonnegInexactReal)
            , (posInexactReal, (tyOr' [posRational, posInexactReal]), nonnegInexactReal)
            , ((tyOr' [posRational, posInexactReal]), posInexactReal, nonnegInexactReal)
            , (inexactReal, (tyOr' [posRational, negRational, inexactReal]), inexactReal)
            , ((tyOr' [posRational, negRational, inexactReal]), inexactReal, inexactReal)
            , (inexactReal, inexactReal, inexactReal)
            , (posReal, posReal, nonnegReal)
            , (negReal, negReal, nonnegReal) -- 0.0 is non-neg, but doesn't preserve sign
            , (negReal, posReal, nonposReal) -- idem
            , (posReal, negReal, nonposReal) -- idem
            , (real, real, real)
            , (floatComplex, floatComplex, floatComplex)
            , (floatComplex, (tyOr' [inexactComplex, inexactReal, posRational, negRational]), floatComplex)
            , ((tyOr' [inexactComplex, inexactReal, posRational, negRational]), floatComplex, floatComplex)
            , (floatComplex, number, floatComplex) -- if any argument after the first is exact 0, not a problem
            , (singleFloatComplex, singleFloatComplex, singleFloatComplex)
            , (singleFloatComplex, (tyOr' [singleFloatComplex, singleFloat, posRational, negRational]), singleFloatComplex)
            , ((tyOr' [singleFloatComplex, singleFloat, posRational, negRational]), singleFloatComplex, singleFloatComplex)
            , (inexactComplex, inexactComplex, inexactComplex)
            , (inexactComplex, (tyOr' [inexactComplex, inexactReal, posRational, negRational]), inexactComplex)
            , ((tyOr' [inexactComplex, inexactReal, posRational, negRational]), inexactComplex, inexactComplex)
            , (number, number, number)]))

  , ("max", (BinOp
              [ (zero, zero, zero)
              , (one, one, one)
              , (one, zero, one)
              , (zero, one, one)
              , (posByte, byte, posByte)
              , (byte, posByte, posByte)
              , (posIndex, index, posIndex)
              , (index, posIndex, posIndex)
              , (posFixnum, fixnum, posFixnum)
              , (fixnum, posFixnum, posFixnum)
              , (nonnegFixnum, fixnum, nonnegFixnum)
              , (fixnum, nonnegFixnum, nonnegFixnum)
              , (index, index, index)
              , (negFixnum, negFixnum, negFixnum)
              , (nonposFixnum, nonposFixnum, nonposFixnum)
              , (posFixnum, posFixnum, posFixnum)
              , (nonnegFixnum, nonnegFixnum, nonnegFixnum)
              , (fixnum, fixnum, fixnum)
              , (posInteger, integer, posInteger)
              , (integer, posInteger, posInteger)
              , (nonnegInteger, integer, nonnegInteger)
              , (integer, nonnegInteger, nonnegInteger)
              , (negInteger, negInteger, negInteger)
              , (nonposInteger, nonposInteger, nonposInteger)
              , (posInteger, posInteger, posInteger)
              , (nonnegInteger, nonnegInteger, nonnegInteger)
              , (integer, integer, integer)
              , (posRational, rational, posRational)
              , (rational, posRational, posRational)
              , (nonnegRational, rational, nonnegRational)
              , (rational, nonnegRational, nonnegRational)
              , (negRational, negRational, negRational)
              , (nonposRational, nonposRational, nonposRational)
              , (posRational, posRational, posRational)
              , (nonnegRational, nonnegRational, nonnegRational)
              , (rational, rational, rational)
              , (floatPosZero, floatPosZero, floatPosZero)
              , (floatNegZero, floatNegZero, floatNegZero)
              , (floatZero, floatZero, floatZero)
              , (posFloat, float, posFloat)
              , (float, posFloat, posFloat)
              , (nonnegFloat, float, nonnegFloat)
              , (float, nonnegFloat, nonnegFloat)
              , (negFloat, negFloat, negFloat)
              , (nonposFloat, nonposFloat, nonposFloat)
              , (posFloat, posFloat, posFloat)
              , (nonnegFloat, nonnegFloat, nonnegFloat)
              , (float, float, float)
              , (singleFloatPosZero, singleFloatPosZero, singleFloatPosZero)
              , (singleFloatNegZero, singleFloatNegZero, singleFloatNegZero)
              , (singleFloatZero, singleFloatZero, singleFloatZero)
              , (posSingleFloat, posSingleFloat, posSingleFloat)
              , (posSingleFloat, singleFloat, posSingleFloat)
              , (singleFloat, posSingleFloat, posSingleFloat)
              , (nonnegSingleFloat, nonnegSingleFloat, nonnegSingleFloat)
              , (nonnegSingleFloat, singleFloat, nonnegSingleFloat)
              , (singleFloat, nonnegSingleFloat, nonnegSingleFloat)
              , (negSingleFloat, negSingleFloat, negSingleFloat)
              , (nonposSingleFloat, nonposSingleFloat, nonposSingleFloat)
              , (singleFloat, singleFloat, singleFloat)
              , (inexactRealPosZero, inexactRealPosZero, inexactRealPosZero)
              , (inexactRealNegZero, inexactRealNegZero, inexactRealNegZero)
              , (inexactRealZero, inexactRealZero, inexactRealZero)
              , (posInexactReal, inexactReal, posInexactReal)
              , (inexactReal, posInexactReal, posInexactReal)
              , (nonnegInexactReal, inexactReal, nonnegInexactReal)
              , (inexactReal, nonnegInexactReal, nonnegInexactReal)
              , (negInexactReal, negInexactReal, negInexactReal)
              , (nonposInexactReal, nonposInexactReal, nonposInexactReal)
              , (posInexactReal, posInexactReal, posInexactReal)
              , (nonnegInexactReal, nonnegInexactReal, nonnegInexactReal)
              , (inexactReal, inexactReal, inexactReal)
              , (realZero, realZero, realZero)
              , (posReal, real, posReal)
              , (real, posReal, posReal)
              , (nonnegReal, real, nonnegReal)
              , (real, nonnegReal, nonnegReal)
              , (negReal, negReal, negReal)
              , (nonposReal, nonposReal, nonposReal)
              , (posReal, posReal, posReal)
              , (nonnegReal, nonnegReal, nonnegReal)
              , (real, real, real)]))

  , ("min", (BinOp
              [ (zero, zero, zero)
              , (one, one, one)
              , (zero, one, zero)
              , (one, zero, zero)
              , (posByte, posByte, posByte)
              , (byte, byte, byte)
              , (posIndex, posIndex, posIndex)
              , (index, index, index)
              , (posFixnum, posFixnum, posFixnum)
              , (nonnegFixnum, nonnegFixnum, nonnegFixnum)
              , (negFixnum, fixnum, negFixnum)
              , (fixnum, negFixnum, negFixnum)
              , (nonposFixnum, fixnum, nonposFixnum)
              , (fixnum, nonposFixnum, nonposFixnum)
              , (posByte, posInteger, posByte)
              , (posInteger, posByte, posByte)
              , (byte, nonnegInteger, byte)
              , (nonnegInteger, byte, byte)
              , (posFixnum, posInteger, posFixnum)
              , (posInteger, posFixnum, posFixnum)
              , (nonnegFixnum, nonnegInteger, nonnegFixnum)
              , (nonnegInteger, nonnegFixnum, nonnegFixnum)
              , (negFixnum, negFixnum, negFixnum)
              , (nonposFixnum, nonposFixnum, nonposFixnum)
              , (fixnum, fixnum, fixnum)
              , (posInteger, posInteger, posInteger)
              , (nonnegInteger, nonnegInteger, nonnegInteger)
              , (negInteger, integer, negInteger)
              , (integer, negInteger, negInteger)
              , (nonposInteger, integer, nonposInteger)
              , (integer, nonposInteger, nonposInteger)
              , (negInteger, negInteger, negInteger)
              , (nonposInteger, nonposInteger, nonposInteger)
              , (integer, integer, integer)
              , (posRational, posRational, posRational)
              , (nonnegRational, nonnegRational, nonnegRational)
              , (negRational, rational, negRational)
              , (rational, negRational, negRational)
              , (nonposRational, rational, nonposRational)
              , (rational, nonposRational, nonposRational)
              , (negRational, negRational, negRational)
              , (nonposRational, nonposRational, nonposRational)
              , (rational, rational, rational)
              , (floatPosZero, floatPosZero, floatPosZero)
              , (floatNegZero, floatNegZero, floatNegZero)
              , (floatZero, floatZero, floatZero)
              , (posFloat, posFloat, posFloat)
              , (nonnegFloat, nonnegFloat, nonnegFloat)
              , (negFloat, float, negFloat)
              , (float, negFloat, negFloat)
              , (nonposFloat, float, nonposFloat)
              , (float, nonposFloat, nonposFloat)
              , (negFloat, negFloat, negFloat)
              , (nonposFloat, nonposFloat, nonposFloat)
              , (float, float, float)
              , (singleFloatPosZero, singleFloatPosZero, singleFloatPosZero)
              , (singleFloatNegZero, singleFloatNegZero, singleFloatNegZero)
              , (singleFloatZero, singleFloatZero, singleFloatZero)
              , (posSingleFloat, posSingleFloat, posSingleFloat)
              , (nonnegSingleFloat, nonnegSingleFloat, nonnegSingleFloat)
              , (negSingleFloat, singleFloat, negSingleFloat)
              , (singleFloat, negSingleFloat, negSingleFloat)
              , (nonposSingleFloat, singleFloat, nonposSingleFloat)
              , (singleFloat, nonposSingleFloat, nonposSingleFloat)
              , (negSingleFloat, negSingleFloat, negSingleFloat)
              , (nonposSingleFloat, nonposSingleFloat, nonposSingleFloat)
              , (singleFloat, singleFloat, singleFloat)
              , (inexactRealPosZero, inexactRealPosZero, inexactRealPosZero)
              , (inexactRealNegZero, inexactRealNegZero, inexactRealNegZero)
              , (inexactRealZero, inexactRealZero, inexactRealZero)
              , (posInexactReal, posInexactReal, posInexactReal)
              , (nonnegInexactReal, nonnegInexactReal, nonnegInexactReal)
              , (negInexactReal, inexactReal, negInexactReal)
              , (inexactReal, negInexactReal, negInexactReal)
              , (nonposInexactReal, inexactReal, nonposInexactReal)
              , (inexactReal, nonposInexactReal, nonposInexactReal)
              , (negInexactReal, negInexactReal, negInexactReal)
              , (nonposInexactReal, nonposInexactReal, nonposInexactReal)
              , (inexactReal, inexactReal, inexactReal)
              , (realZero, realZero, realZero)
              , (posReal, posReal, posReal)
              , (nonnegReal, nonnegReal, nonnegReal)
              , (negReal, real, negReal)
              , (real, negReal, negReal)
              , (nonposReal, real, nonposReal)
              , (real, nonposReal, nonposReal)
              , (negReal, negReal, negReal)
              , (nonposReal, nonposReal, nonposReal)
              , (real, real, real)]))

  , ("<", (CompOp
           [ (integer, one, (IsA ArgZero nonposInteger), (IsA ArgZero posInteger))
           , (real, zero, (IsA ArgZero negReal), (IsA ArgZero nonnegReal))
           , (zero, real, (IsA ArgOne posReal), (IsA ArgOne nonposReal))
           , (real, realZero, (IsA ArgZero negReal), TT) -- False says nothing because of NaN
           , (realZero, real, (IsA ArgOne posReal), TT) -- False says nothing because of NaN
           , (byte, posByte, TT, (IsA ArgZero posByte))
           , (byte, byte, (IsA ArgOne posByte), TT)
           , (posInteger, byte, (Conj (IsA ArgZero posByte) (IsA ArgOne posByte)), TT)
           , (posReal, byte, (IsA ArgOne posByte), TT) -- posReal is ok here, no prop for #f
           , (byte, posInteger, TT, (Conj (IsA ArgZero posByte) (IsA ArgOne posByte)))
           , (byte, posRational, TT, (IsA ArgZero posByte)) -- can't be posReal, which includes NaN
           , (nonnegInteger, byte, (Conj (IsA ArgZero byte) (IsA ArgOne posByte)), TT)
           , (nonnegReal, byte, (IsA ArgOne posByte), TT)
           , (byte, nonnegInteger, TT, (IsA ArgOne byte))
           , (index, posIndex, TT, (IsA ArgZero posIndex))
           , (index, index, (IsA ArgOne posIndex), TT)
           , (posInteger, index, (Conj (IsA ArgZero posIndex) (IsA ArgOne posIndex)), TT)
           , (posReal, index, (IsA ArgOne posIndex), TT)
           , (index, posInteger, TT, (Conj (IsA ArgZero posIndex) (IsA ArgOne posIndex)))
           , (index, posRational, TT, (IsA ArgZero posIndex)) -- can't be posReal, which includes NaN
           , (nonnegInteger, index, (Conj (IsA ArgZero index) (IsA ArgOne posIndex)), TT)
           , (nonnegReal, index, (IsA ArgOne posIndex), TT)
           , (index, nonnegInteger, TT, (IsA ArgOne index))
           , (fixnum, posInteger, TT, (Conj (IsA ArgZero posFixnum) (IsA ArgOne posFixnum)))
           , (fixnum, posRational, TT, (IsA ArgZero posFixnum))
           , (fixnum, nonnegInteger, TT, (Conj (IsA ArgZero nonnegFixnum) (IsA ArgOne nonnegFixnum)))
           , (fixnum, nonnegRational, TT, (IsA ArgZero nonnegFixnum))
           , (nonnegInteger, fixnum, (Conj (IsA ArgZero nonnegFixnum) (IsA ArgOne posFixnum)), TT)
           , (nonnegReal, fixnum, (IsA ArgOne posFixnum), TT)
           , (fixnum, nonposInteger, (Conj (IsA ArgZero negFixnum) (IsA ArgOne nonposFixnum)), TT)
           , (fixnum, nonposReal, (IsA ArgZero negFixnum), TT)
           , (negInteger, fixnum, TT, (Conj (IsA ArgZero negFixnum) (IsA ArgOne negFixnum)))
           , (negRational, fixnum, TT, (IsA ArgOne negFixnum))
           , (nonposInteger, fixnum, TT, (Conj (IsA ArgZero nonposFixnum) (IsA ArgOne nonposFixnum)))
           , (nonposRational, fixnum, TT, (IsA ArgOne nonposFixnum))
           , (real, posInfinity, (IsA ArgZero (tyNot (tyOr' [inexactRealNaN, posInfinity]))), (IsA ArgZero (tyOr' [inexactRealNaN, posInfinity])))
           , (negInfinity, real, (IsA ArgOne (tyNot (tyOr' [inexactRealNaN, negInfinity]))), (IsA ArgOne (tyOr' [inexactRealNaN, negInfinity])))
           , (posInfinity, real, FF, TT)
           , (real, negInfinity, FF, TT)
           , (integer, zero, (IsA ArgZero negInteger), (IsA ArgZero nonnegInteger)) -- <-type-pattern integer
           , (zero, integer, (IsA ArgOne posInteger), (IsA ArgOne nonposInteger))
           , (integer, posRealNoNaN, TT, (IsA ArgZero posInteger)) -- AMK added NoNaN
           , (integer, nonnegRealNoNaN, TT, (IsA ArgZero nonnegInteger)) -- AMK added NoNaN
           , (nonnegReal, integer, (IsA ArgOne posInteger), TT)
           , (integer, nonposReal, (IsA ArgZero negInteger), TT)
           , (negRealNoNaN, integer, TT, (IsA ArgOne negInteger)) -- AMK added NoNaN
           , (nonposRealNoNaN, integer, TT, (IsA ArgOne nonposInteger)) -- AMK added NoNaN
           , (rational, zero, (IsA ArgZero negRational), (IsA ArgZero nonnegRational)) -- <-type-pattern rational
           , (zero, rational, (IsA ArgOne posRational), (IsA ArgOne nonposRational))
           , (rational, posRealNoNaN, TT, (IsA ArgZero posRational)) -- AMK added NoNaN
           , (rational, nonnegRealNoNaN, TT, (IsA ArgZero nonnegRational)) -- AMK added NoNaN
           , (nonnegReal, rational, (IsA ArgOne posRational), TT)
           , (rational, nonposReal, (IsA ArgZero negRational), TT)
           , (negRealNoNaN, rational, TT, (IsA ArgOne negRational)) -- AMK added NoNaN
           , (nonposRealNoNaN, rational, TT, (IsA ArgOne nonposRational)) -- AMK added NoNaN
           , (float, realZero, (IsA ArgZero negFloat), TT) -- <-type-pattern float
           , (realZero, float, (IsA ArgOne posFloat), TT)
           , (float, posReal, TT, TT)
           , (float, nonnegReal, TT, TT)
           , (nonnegReal, float, (IsA ArgOne posFloat), TT)
           , (float, nonposReal, (IsA ArgZero negFloat), TT)
           , (negReal, float, TT, TT)
           , (nonposReal, float, TT, TT)
           , (singleFloat, realZero, (IsA ArgZero negSingleFloat), TT) -- <-type-pattern single-Float
           , (realZero, singleFloat, (IsA ArgOne posSingleFloat), TT)
           , (singleFloat, posReal, TT, TT)
           , (singleFloat, nonnegReal, TT, TT)
           , (nonnegReal, singleFloat, (IsA ArgOne posSingleFloat), TT)
           , (singleFloat, nonposReal, (IsA ArgZero negSingleFloat), TT)
           , (negReal, singleFloat, TT, TT)
           , (nonposReal, singleFloat, TT, TT)
           , (inexactReal, realZero, (IsA ArgZero negInexactReal), TT) -- <-type-pattern inexactreal
           , (realZero, inexactReal, (IsA ArgOne posInexactReal), TT)
           , (inexactReal, posReal, TT, TT)
           , (inexactReal, nonnegReal, TT, TT)
           , (nonnegReal, inexactReal, (IsA ArgOne posInexactReal), TT)
           , (inexactReal, nonposReal, (IsA ArgZero negInexactReal), TT)
           , (negReal, inexactReal, TT, TT)
           , (nonposReal, inexactReal, TT, TT)
           , (real, realZero, (IsA ArgZero negReal), TT) -- <-type-pattern real
           , (realZero, real, (IsA ArgOne posReal), TT)
           , (real, posReal, TT, TT)
           , (real, nonnegReal, TT, TT)
           , (nonnegReal, real, (IsA ArgOne posReal), TT)
           , (real, nonposReal, (IsA ArgZero negReal), TT)
           , (negReal, real, TT, TT)
           , (nonposReal, real, TT, TT) -- end of <-type-pattern
           , (real, real, TT, TT)]))
    
  , ("<=", (CompOp
             [ (integer, one, (IsA ArgZero (tyOr' [nonposInteger, one])), (IsA ArgZero posInteger))
             , (one, integer, (IsA ArgOne posInteger), (IsA ArgOne nonposInteger))
             , (real, zero, (IsA ArgZero nonposReal), (IsA ArgZero posReal))
             , (zero, real, (IsA ArgOne nonnegReal), (IsA ArgOne negReal))
             , (real, realZero, (IsA ArgZero nonposReal), TT) -- False says nothing because of NaN
             , (realZero, real, (IsA ArgZero nonnegReal), TT) -- False says nothing because of NaN
             , (posByte, byte, (IsA ArgOne posByte), TT)
             , (byte, byte, TT, (IsA ArgZero posByte))
             , (posInteger, byte, (Conj (IsA ArgZero posByte) (IsA ArgOne posByte)), TT)
             , (posReal, byte, (IsA ArgOne posByte), TT)
             , (byte, posInteger, TT, (Conj (IsA ArgZero posByte) (IsA ArgOne posByte)))
             , (byte, posRational, TT, (IsA ArgZero posByte))
             , (nonnegInteger, byte, (IsA ArgZero byte), TT)
             , (byte, nonnegInteger, TT, (Conj (IsA ArgZero posByte) (IsA ArgOne byte)))
             , (byte, nonnegRational, TT, (IsA ArgZero posByte))
             , (posIndex, index, (IsA ArgOne posIndex), TT)
             , (index, index, TT, (IsA ArgZero posIndex))
             , (posInteger, index, (Conj (IsA ArgZero posIndex) (IsA ArgOne posIndex)), TT)
             , (posReal, index, (IsA ArgOne posIndex), TT)
             , (index, posInteger, TT, (Conj (IsA ArgZero posIndex) (IsA ArgOne posIndex)))
             , (index, posRational, TT, (IsA ArgZero posIndex))
             , (nonnegInteger, index, (IsA ArgZero index), TT)
             , (index, nonnegInteger, TT, (Conj (IsA ArgZero posIndex) (IsA ArgOne index)))
             , (index, nonnegRational, TT, (IsA ArgZero posIndex))
             , (posInteger, fixnum, (Conj (IsA ArgZero posFixnum) (IsA ArgOne posFixnum)), TT)
             , (posReal, fixnum, (IsA ArgOne posFixnum), TT)
             , (nonnegInteger, fixnum, (Conj (IsA ArgZero nonnegFixnum) (IsA ArgOne nonnegFixnum)), TT)
             , (nonnegReal, fixnum, (IsA ArgOne nonnegFixnum), TT)
             , (fixnum, nonnegInteger, TT, (Conj (IsA ArgZero posFixnum) (IsA ArgOne nonnegFixnum)))
             , (fixnum, nonnegRational, TT, (IsA ArgZero posFixnum))
             , (nonposInteger, fixnum, TT, (Conj (IsA ArgZero nonposFixnum) (IsA ArgOne negFixnum)))
             , (nonposRational, fixnum, TT, (IsA ArgOne negFixnum))
             , (fixnum, negInteger, (Conj (IsA ArgZero negFixnum) (IsA ArgOne negFixnum)), TT)
             , (fixnum, negReal, (IsA ArgZero negFixnum), TT)
             , (fixnum, nonposInteger, (Conj (IsA ArgZero nonposFixnum) (IsA ArgOne nonposFixnum)), TT)
             , (fixnum, nonposReal, (IsA ArgZero nonposFixnum), TT)
             , (real, posInfinity, (IsA ArgZero (tyNot inexactRealNaN)), (IsA ArgZero inexactRealNaN))
             , (negInfinity, real, (IsA ArgOne (tyNot inexactRealNaN)), (IsA ArgOne inexactRealNaN))
             , (posInfinity, real, (IsA ArgOne posInfinity), (IsA ArgOne (tyNot posInfinity)))
             , (real, negInfinity, (IsA ArgZero negInfinity), (IsA ArgZero (tyNot negInfinity)))
             , (integer, zero, (IsA ArgZero nonposInteger), (IsA ArgZero posInteger)) -- <=-pat integer
             , (zero, integer, (IsA ArgOne nonnegInteger), (IsA ArgOne negInteger)) -- <=-pat integer
             , (integer, nonnegRealNoNaN, TT, (IsA ArgZero posInteger)) -- <=-pat integer
             , (posReal, integer, (IsA ArgOne posInteger), TT) -- <=-pat integer
             , (nonnegReal, integer, (IsA ArgOne nonnegInteger), TT) -- <=-pat integer
             , (nonposRealNoNaN, integer, TT, (IsA ArgOne negInteger)) -- <=-pat integer
             , (integer, negReal, (IsA ArgZero negInteger), TT) -- <=-pat integer
             , (integer, nonposReal, (IsA ArgZero nonposInteger), TT) -- <=-pat integer
             , (rational, zero, (IsA ArgZero nonposRational), (IsA ArgZero posRational)) -- <=-pat rational
             , (zero, rational, (IsA ArgOne nonnegRational), (IsA ArgOne negRational)) -- <=-pat rational
             , (rational, nonnegRealNoNaN, TT, (IsA ArgZero posRational)) -- <=-pat rational
             , (posReal, rational, (IsA ArgOne posRational), TT) -- <=-pat rational
             , (nonnegReal, rational, (IsA ArgOne nonnegRational), TT) -- <=-pat rational
             , (nonposRealNoNaN, rational, TT, (IsA ArgOne negRational)) -- <=-pat rational
             , (rational, negReal, (IsA ArgZero negRational), TT) -- <=-pat rational
             , (rational, nonposReal, (IsA ArgZero nonposRational), TT) -- <=-pat rational
             , (float, realZeroNoNaN, (IsA ArgZero nonposFloat), TT) -- <=-pat float
             , (realZeroNoNaN, float, (IsA ArgOne nonnegFloat), TT) -- <=-pat float
             , (float, nonnegRealNoNaN, TT, TT) -- <=-pat float
             , (posReal, float, (IsA ArgOne posFloat), TT) -- <=-pat float
             , (nonnegReal, float, (IsA ArgOne nonnegFloat), TT) -- <=-pat float
             , (nonposRealNoNaN, float, TT, TT) -- <=-pat float
             , (float, negReal, (IsA ArgZero negFloat), TT) -- <=-pat float
             , (float, nonposReal, (IsA ArgZero nonposFloat), TT) -- <=-pat float
             , (singleFloat, realZeroNoNaN, (IsA ArgZero nonposSingleFloat), TT) -- <=-pat singleFloat
             , (realZeroNoNaN, singleFloat, (IsA ArgOne nonnegSingleFloat), TT) -- <=-pat singleFloat
             , (singleFloat, nonnegRealNoNaN, TT, TT) -- <=-pat singleFloat
             , (posReal, singleFloat, (IsA ArgOne posSingleFloat), TT) -- <=-pat singleFloat
             , (nonnegReal, singleFloat, (IsA ArgOne nonnegSingleFloat), TT) -- <=-pat singleFloat
             , (nonposRealNoNaN, singleFloat, TT, TT) -- <=-pat singleFloat
             , (singleFloat, negReal, (IsA ArgZero negSingleFloat), TT) -- <=-pat singleFloat
             , (singleFloat, nonposReal, (IsA ArgZero nonposSingleFloat), TT) -- <=-pat singleFloat
             , (inexactReal, realZeroNoNaN, (IsA ArgZero nonposInexactReal), TT) -- <=-pat inexactReal
             , (realZeroNoNaN, inexactReal, (IsA ArgOne nonnegInexactReal), TT) -- <=-pat inexactReal
             , (inexactReal, nonnegRealNoNaN, TT, TT) -- <=-pat inexactReal
             , (posReal, inexactReal, (IsA ArgOne posInexactReal), TT) -- <=-pat inexactReal
             , (nonnegReal, inexactReal, (IsA ArgOne nonnegInexactReal), TT) -- <=-pat inexactReal
             , (nonposRealNoNaN, inexactReal, TT, TT) -- <=-pat inexactReal
             , (inexactReal, negReal, (IsA ArgZero negInexactReal), TT) -- <=-pat inexactReal
             , (inexactReal, nonposReal, (IsA ArgZero nonposInexactReal), TT) -- <=-pat inexactReal
             , (real, realZeroNoNaN, (IsA ArgZero nonposReal), TT) -- <=-pat real
             , (realZeroNoNaN, real, (IsA ArgOne nonnegReal), TT) -- <=-pat real
             , (real, nonnegRealNoNaN, TT, TT) -- <=-pat real
             , (posReal, real, (IsA ArgOne posReal), TT) -- <=-pat real
             , (nonnegReal, real, (IsA ArgOne nonnegReal), TT) -- <=-pat real
             , (nonposRealNoNaN, real, TT, TT) -- <=-pat real
             , (real, negReal, (IsA ArgZero negReal), TT) -- <=-pat real
             , (real, nonposReal, (IsA ArgZero nonposReal), TT) -- <=-pat real
             , (real, real, TT, TT)]))

  , ("=", (CompOp
            [ (real, realZeroNoNaN, (IsA ArgZero realZeroNoNaN), (IsA ArgZero (tyNot realZeroNoNaN)))
            , (realZeroNoNaN, real, (IsA ArgOne realZeroNoNaN), (IsA ArgOne (tyNot realZeroNoNaN)))
            , (exactNumber, one, (IsA ArgZero one), TT)
            , (one, exactNumber, (IsA ArgOne one), TT)
            , (exactNumber, posByte, (IsA ArgZero posByte), TT)
            , (posByte, exactNumber, (IsA ArgOne posByte), TT)
            , (exactNumber, byte, (IsA ArgZero byte), TT)
            , (byte, exactNumber, (IsA ArgOne byte), TT)
            , (exactNumber, posIndex, (IsA ArgZero posIndex), TT)
            , (posIndex, exactNumber, (IsA ArgOne posIndex), TT)
            , (exactNumber, index, (IsA ArgZero index), TT)
            , (index, exactNumber, (IsA ArgOne index), TT)
            , (exactNumber, posFixnum, (IsA ArgZero posFixnum), TT)
            , (posFixnum, exactNumber, (IsA ArgOne posFixnum), TT)
            , (exactNumber, nonnegFixnum, (IsA ArgZero nonnegFixnum), TT)
            , (nonnegFixnum, exactNumber, (IsA ArgOne nonnegFixnum), TT)
            , (exactNumber, negFixnum, (IsA ArgZero negFixnum), TT)
            , (negFixnum, exactNumber, (IsA ArgOne negFixnum), TT)
            , (exactNumber, nonposFixnum, (IsA ArgZero nonposFixnum), TT)
            , (nonposFixnum, exactNumber, (IsA ArgOne nonposFixnum), TT)
            , (exactNumber, fixnum, (IsA ArgZero fixnum), TT)
            , (fixnum, exactNumber, (IsA ArgOne fixnum), TT)
            , (exactNumber, posInteger, (IsA ArgZero posInteger), TT)
            , (posInteger, exactNumber, (IsA ArgOne posInteger), TT)
            , (exactNumber, nonnegInteger, (IsA ArgZero nonnegInteger), TT)
            , (nonnegInteger, exactNumber, (IsA ArgOne nonnegInteger), TT)
            , (exactNumber, negInteger, (IsA ArgZero negInteger), TT)
            , (negInteger, exactNumber, (IsA ArgOne negInteger), TT)
            , (exactNumber, nonposInteger, (IsA ArgZero nonposInteger), TT)
            , (nonposInteger, exactNumber, (IsA ArgOne nonposInteger), TT)
            , (exactNumber, integer, (IsA ArgZero integer), TT)
            , (integer, exactNumber, (IsA ArgOne integer), TT)
            , (exactNumber, posRational, (IsA ArgZero posRational), TT)
            , (posRational, exactNumber, (IsA ArgOne posRational), TT)
            , (exactNumber, nonnegRational, (IsA ArgZero nonnegRational), TT)
            , (nonnegRational, exactNumber, (IsA ArgOne nonnegRational), TT)
            , (exactNumber, negRational, (IsA ArgZero negRational), TT)
            , (negRational, exactNumber, (IsA ArgOne negRational), TT)
            , (exactNumber, nonposRational, (IsA ArgZero nonposRational), TT)
            , (nonposRational, exactNumber, (IsA ArgOne nonposRational), TT)
            , (exactNumber, rational, (IsA ArgZero rational), TT)
            , (rational, exactNumber, (IsA ArgOne rational), TT)
            , (exactNumber, exactNumber, (IsA ArgZero exactNumber), TT)
            , (exactNumber, exactNumber, (IsA ArgOne exactNumber), TT)
            , (real, realZero, (IsA ArgZero realZero), TT)
            , (realZero, real, (IsA ArgOne realZero), TT)
            , (real, posReal, (IsA ArgZero posReal), TT)
            , (posReal, real, (IsA ArgOne posReal), TT)
            , (real, nonnegReal, (IsA ArgZero nonnegReal), TT)
            , (nonnegReal, real, (IsA ArgOne nonnegReal), TT)
            , (real, negReal, (IsA ArgZero negReal), TT)
            , (negReal, real, (IsA ArgOne negReal), TT)
            , (real, nonposReal, (IsA ArgZero nonposReal), TT)
            , (nonposReal, real, (IsA ArgOne nonposReal), TT)
            , (real, real, (IsA ArgZero real), TT)
            , (real, real, (IsA ArgOne real), TT)
            , (number, number, TT, TT)]))
  ] -- end of opTypes

