#lang racket/base

(require redex/reduction-semantics
         racket/match
         "lang-syntax.rkt")

(provide (all-defined-out))

(define-metafunction sot
  nop1-type : nop1 -> τ
  [(nop1-type add1)
   (And* (Arrow Zero One)
       & (Arrow One Byte)
       & (Arrow Byte Index)
       & (Arrow Index Fixnum)
       & (Arrow Integer Integer)
       & (Arrow Rational Rational)
       & (Arrow Float Float)
       & (Arrow SingleFloat SingleFloat)
       & (Arrow FloatComplex FloatComplex)
       & (Arrow SingleFloatComplex SingleFloatComplex)
       & (Arrow NonposFixnum Fixnum)
       & (Arrow NegInteger NonposInteger)
       & (Arrow NonnegReal PosReal)
       & (Arrow Number Number))]
  [(nop1-type sub1)
   (And* (Arrow One Zero)
       & (Arrow PosByte Byte)
       & (Arrow PosIndex Index)
       & (Arrow NonnegFixnum Fixnum)
       & (Arrow PosInteger NonnegInteger)
       & (Arrow Integer Integer)
       & (Arrow Rational Rational)
       & (Arrow Float Float)
       & (Arrow SingleFloat SingleFloat)
       & (Arrow NonposReal NegReal)
       & (Arrow FloatComplex FloatComplex)
       & (Arrow SingleFloatComplex SingleFloatComplex)
       & (Arrow Number Number))]
  [(nop1-type abs)
   (And* (Arrow RealZero RealZero)
       & (Arrow Integer NonnegInteger)
       & (Arrow Rational NonnegRational)
       & (Arrow Float NonnegFloat)
       & (Arrow SingleFloat NonnegSingleFloat)
       & (Arrow (Or PosReal NegReal) PosReal))]
  [(nop1-type sqr)
   (And* (Arrow Zero Zero)
       & (Arrow One One)
       & (Arrow Byte Index)
       & (Arrow Integer NonnegInteger)
       & (Arrow PosRational PosRational)
       & (Arrow Rational NonnegRational)
       & (Arrow Float NonnegFloat)
       & (Arrow SingleFloat NonnegSingleFloat)
       & (Arrow FloatComplex FloatComplex)
       & (Arrow SingleFloatComplex SingleFloatComplex)
       & (Arrow ExactNumber ExactNumber)
       & (Arrow Number Number))]
  [(nop1-type sqrt)
   (And* (Arrow Zero Zero)
       & (Arrow One One)
       & (Arrow NonnegFloat NonnegFloat)
       & (Arrow NonnegSingleFloat NonnegSingleFloat)
       & (Arrow InexactRealPosZero InexactRealPosZero)
       & (Arrow InexactRealNegZero InexactRealNegZero)
       & (Arrow RealZero RealZero)
       & (Arrow PosReal PosReal)
       & (Arrow FloatComplex FloatComplex)
       & (Arrow SingleFloatComplex SingleFloatComplex)
       & (Arrow Number Number))])


(define-metafunction sot
  nop2-type : nop2 -> τ
  [(nop2-type +)
   (And* (Arrow (Prod Byte Byte) Index)
       & (Arrow (Prod Index Index) NonnegFixnum)
       & (Arrow (Prod NegFixnum One) NonposFixnum)
       & (Arrow (Prod One NegFixnum) NonposFixnum)
       & (Arrow (Prod NonposFixnum NonnegFixnum) Fixnum)
       & (Arrow (Prod NonnegFixnum NonposFixnum) Fixnum)
       & (Arrow (Prod Integer Integer) Integer)
       & (Arrow (Prod Float Real) Float)
       & (Arrow (Prod Real Float) Float)
       & (Arrow (Prod SingleFloat (Or Rational SingleFloat)) SingleFloat)
       & (Arrow (Prod (Or Rational SingleFloat) SingleFloat) SingleFloat)
       & (Arrow (Prod PosReal NonnegReal) PosReal)
       & (Arrow (Prod NonnegReal PosReal) PosReal)
       & (Arrow (Prod NegReal NonposReal) NegReal)
       & (Arrow (Prod NonposReal NegReal) NegReal)
       & (Arrow (Prod NonnegReal NonnegReal) NonnegReal)
       & (Arrow (Prod NonposReal NonposReal) NonposReal)
       & (Arrow (Prod Real Real) Real)
       & (Arrow (Prod ExactNumber ExactNumber) ExactNumber)
       & (Arrow (Prod FloatComplex Number) FloatComplex)
       & (Arrow (Prod Number FloatComplex) FloatComplex)
       & (Arrow (Prod Float InexactComplex) FloatComplex)
       & (Arrow (Prod InexactComplex Float) FloatComplex)
       & (Arrow (Prod SingleFloatComplex (Or Rational (Or SingleFloat SingleFloatComplex))) SingleFloatComplex)
       & (Arrow (Prod (Or Rational (Or SingleFloat SingleFloatComplex)) SingleFloatComplex) SingleFloatComplex)
       & (Arrow (Prod Number Number) Number))]
  [(nop2-type -)
   (And* (Arrow (Prod Zero PosReal) NegReal)
       & (Arrow (Prod Zero NonnegReal) NonposReal)
       & (Arrow (Prod Zero NegReal) PosReal)
       & (Arrow (Prod Zero NonposReal) NonnegReal)
       & (Arrow (Prod One One) Zero)
       & (Arrow (Prod PosByte One) Byte)
       & (Arrow (Prod PosIndex One) Index)
       & (Arrow (Prod PosInteger One) NonnegInteger)
       & (Arrow (Prod NonnegFixnum NonnegFixnum) Fixnum)
       & (Arrow (Prod NegFixnum NonposFixnum) Fixnum)
       & (Arrow (Prod Integer Integer) Integer)
       & (Arrow (Prod PosRational NonposRational) PosRational)
       & (Arrow (Prod NegRational NonnegRational) NegRational)
       & (Arrow (Prod Float Real) Float)
       & (Arrow (Prod Real Float) Float)
       & (Arrow (Prod SingleFloat (Or SingleFloat Rational)) SingleFloat)
       & (Arrow (Prod (Or SingleFloat Rational) SingleFloat) SingleFloat)
       & (Arrow (Prod Real Real) Real)
       & (Arrow (Prod ExactNumber ExactNumber) ExactNumber)
       & (Arrow (Prod FloatComplex Number) FloatComplex)
       & (Arrow (Prod Number FloatComplex) FloatComplex)
       & (Arrow (Prod SingleFloatComplex (Or SingleFloatComplex ExactNumber)) SingleFloatComplex)
       & (Arrow (Prod (Or SingleFloatComplex ExactNumber) SingleFloatComplex) SingleFloatComplex)
       & (Arrow (Prod Number Number) Number))]
  [(nop2-type *)
   (And* (Arrow (Prod Zero Number) Zero)
       & (Arrow (Prod Number Zero) Zero)
       & (Arrow (Prod Byte Byte) Index)
       & (Arrow (Prod Integer Integer) Integer)
       & (Arrow (Prod (And Rational (Not Zero)) (And Rational (Not Zero))) (And Rational (Not Zero)))
       & (Arrow (Prod Float (Or PosReal NegReal)) Float)
       & (Arrow (Prod (Or PosReal NegReal) Float) Float)
       & (Arrow (Prod Float Float) Float)
       & (Arrow (Prod SingleFloat (Or PosRational (Or NegRational SingleFloat))) SingleFloat)
       & (Arrow (Prod (Or PosRational (Or NegRational SingleFloat)) SingleFloat) SingleFloat)
       & (Arrow (Prod InexactReal InexactReal) InexactReal)
       & (Arrow (Prod NonnegReal NonnegReal) NonnegReal)
       & (Arrow (Prod NonposReal NonposReal) NonnegReal)
       & (Arrow (Prod NonposReal NonnegReal) NonposReal)
       & (Arrow (Prod NonnegReal NonposReal) NonposReal)
       & (Arrow (Prod FloatComplex (Or InexactComplex (Or InexactReal (Or PosRational NegRational)))) FloatComplex)
       & (Arrow (Prod (Or InexactComplex (Or InexactReal (Or PosRational NegRational))) FloatComplex) FloatComplex)
       & (Arrow (Prod SingleFloatComplex (Or SingleFloatComplex (Or SingleFloat (Or PosRational NegRational)))) SingleFloatComplex)
       & (Arrow (Prod (Or SingleFloatComplex (Or SingleFloat (Or PosRational NegRational))) SingleFloatComplex) SingleFloatComplex)
       & (Arrow (Prod InexactComplex (Or InexactComplex (Or InexactReal (Or PosRational NegRational)))) InexactComplex)
       & (Arrow (Prod (Or InexactComplex (Or InexactReal (Or PosRational NegRational))) InexactComplex) InexactComplex)
       & (Arrow (Prod Number Number) Number))]
  [(nop2-type /)
   (And* (Arrow (Prod Number Zero) Empty)
       & (Arrow (Prod Zero Number) Zero)
       & (Arrow (Prod One One) One)
       & (Arrow (Prod (And Rational (Not Zero)) (And Rational (Not Zero))) (And Rational (Not Zero)))
       & (Arrow (Prod (Or PosReal (Or NegReal Float)) Float) Float)
       & (Arrow (Prod Float Real) Float)
       & (Arrow (Prod SingleFloat (Or PosRational (Or NegRational SingleFloat))) SingleFloat)
       & (Arrow (Prod (Or PosRational (Or NegRational SingleFloat)) SingleFloat) SingleFloat)
       & (Arrow (Prod InexactReal InexactReal) InexactReal)
       & (Arrow (Prod PosReal PosReal) NonnegReal)
       & (Arrow (Prod NegReal NegReal) NonnegReal)
       & (Arrow (Prod NegReal PosReal) NonposReal)
       & (Arrow (Prod PosReal NegReal) NonposReal)
       & (Arrow (Prod (Or InexactComplex (Or InexactReal (Or PosRational NegRational))) FloatComplex) FloatComplex)
       & (Arrow (Prod FloatComplex Number) FloatComplex)
       & (Arrow (Prod SingleFloatComplex (Or SingleFloatComplex (Or SingleFloat (Or PosRational NegRational)))) SingleFloatComplex)
       & (Arrow (Prod (Or SingleFloatComplex (Or SingleFloat (Or PosRational NegRational))) SingleFloatComplex) SingleFloatComplex)
       & (Arrow (Prod InexactComplex (Or InexactComplex (Or InexactReal (Or PosRational NegRational)))) InexactComplex)
       & (Arrow (Prod (Or InexactComplex (Or InexactReal (Or PosRational NegRational))) InexactComplex) InexactComplex)
       & (Arrow (Prod Number Number) Number))]
  [(nop2-type max)
   (And* (Arrow (Prod One One) One)
       & (Arrow (Prod One Zero) One)
       & (Arrow (Prod Zero One) One)
       & (Arrow (Prod PosByte Byte) PosByte)
       & (Arrow (Prod Byte PosByte) PosByte)
       & (Arrow (Prod Index Index) Index)
       & (Arrow (Prod Fixnum Fixnum) Fixnum)
       & (Arrow (Prod Integer Integer) Integer)
       & (Arrow (Prod Rational Rational) Rational)
       & (Arrow (Prod Float Float) Float)
       & (Arrow (Prod SingleFloat SingleFloat) SingleFloat)
       & (Arrow (Prod InexactRealPosZero InexactRealPosZero) InexactRealPosZero)
       & (Arrow (Prod InexactRealNegZero InexactRealNegZero) InexactRealNegZero)
       & (Arrow (Prod InexactReal InexactReal) InexactReal)
       & (Arrow (Prod PosReal Real) PosReal)
       & (Arrow (Prod Real PosReal) PosReal)
       & (Arrow (Prod NonnegReal Real) NonnegReal)
       & (Arrow (Prod Real NonnegReal) NonnegReal)
       & (Arrow (Prod NegReal NegReal) NegReal)
       & (Arrow (Prod NonposReal NonposReal) NonposReal))]
  [(nop2-type min)
   (And* (Arrow (Prod One One) One)
       & (Arrow (Prod Index Index) Index)
       & (Arrow (Prod Byte NonnegInteger) Byte)
       & (Arrow (Prod NonnegInteger Byte) Byte)
       & (Arrow (Prod NonnegFixnum NonnegInteger) NonnegFixnum)
       & (Arrow (Prod NonnegInteger NonnegFixnum) NonnegFixnum)
       & (Arrow (Prod Fixnum Fixnum) Fixnum)
       & (Arrow (Prod Integer Integer) Integer)
       & (Arrow (Prod Rational Rational) Rational)
       & (Arrow (Prod Float Float) Float)
       & (Arrow (Prod SingleFloat SingleFloat) SingleFloat)
       & (Arrow (Prod InexactRealPosZero InexactRealPosZero) InexactRealPosZero)
       & (Arrow (Prod InexactRealNegZero InexactRealNegZero) InexactRealNegZero)
       & (Arrow (Prod InexactReal InexactReal) InexactReal)
       & (Arrow (Prod PosReal PosReal) PosReal)
       & (Arrow (Prod NonnegReal NonnegReal) NonnegReal)
       & (Arrow (Prod NegReal Real) NegReal)
       & (Arrow (Prod Real NegReal) NegReal)
       & (Arrow (Prod NonposReal Real) NonposReal)
       & (Arrow (Prod Real NonposReal) NonposReal))]
  [(nop2-type <)
   (And* (Arrow (Prod RealNoNaN RealNoNaN) Boolean)
       & (Arrow (Prod SomeNaN Real) False)
       & (Arrow (Prod Real SomeNaN) False)
       & (Arrow (Prod NonposRealNoNaN PosRealNoNaN) True)
       & (Arrow (Prod PosReal NonposReal) False)
       & (Arrow (Prod NegRealNoNaN RealZeroNoNaN) True)
       & (Arrow (Prod RealZero NegReal) False)
       & (Arrow (Prod NegInfinity (And RealNoNaN (Not NegInfinity))) True)
       & (Arrow (Prod Real NegInfinity) False)
       & (Arrow (Prod NegIntegerNotFixnum (And Integer (Not NegIntegerNotFixnum))) True)
       & (Arrow (Prod (And Integer (Not NegIntegerNotFixnum)) NegIntegerNotFixnum) False)
       & (Arrow (Prod RealZero RealZero) False)
       & (Arrow (Prod One One) False)
       & (Arrow (Prod One (And PosInteger (Not One))) True)
       & (Arrow (Prod (And PosInteger (Not One)) One) False)
       & (Arrow (Prod Byte PosIntegerNotByte) True)
       & (Arrow (Prod PosIntegerNotByte Byte) False)
       & (Arrow (Prod Index PosIntegerNotIndex) True)
       & (Arrow (Prod PosIntegerNotIndex Index) False)
       & (Arrow (Prod Fixnum PosIntegerNotFixnum) True)
       & (Arrow (Prod PosIntegerNotFixnum Fixnum) False)
       & (Arrow (Prod (And RealNoNaN (Not PosInfinity)) PosInfinity) True)
       & (Arrow (Prod PosInfinity Real) False))]
  [(nop2-type <=)
   (And* (Arrow (Prod RealNoNaN RealNoNaN) Boolean)
       & (Arrow (Prod SomeNaN Real) False)
       & (Arrow (Prod Real SomeNaN) False)
       & (Arrow (Prod NegRealNoNaN NonnegRealNoNaN) True)
       & (Arrow (Prod NonnegRealNoNaN NegRealNoNaN) False)
       & (Arrow (Prod RealZeroNoNaN RealZeroNoNaN) True)
       & (Arrow (Prod NonposRealNoNaN PosRealNoNaN) True)
       & (Arrow (Prod PosRealNoNaN NonposRealNoNaN) False)
       & (Arrow (Prod NegInfinity RealNoNaN) True)
       & (Arrow (Prod (And RealNoNaN (Not NegInfinity)) NegInfinity) False)
       & (Arrow (Prod NegIntegerNotFixnum (And Integer (Not NegIntegerNotFixnum))) True)
       & (Arrow (Prod (And Integer (Not NegIntegerNotFixnum)) NegIntegerNotFixnum) False)
       & (Arrow (Prod One PosInteger) True)
       & (Arrow (Prod (And PosInteger (Not One)) One) False)
       & (Arrow (Prod Byte PosIntegerNotByte) True)
       & (Arrow (Prod PosIntegerNotByte Byte) False)
       & (Arrow (Prod Index PosIntegerNotIndex) True)
       & (Arrow (Prod PosIntegerNotIndex Index) False)
       & (Arrow (Prod Fixnum PosIntegerNotFixnum) True)
       & (Arrow (Prod PosIntegerNotFixnum Fixnum) False)
       & (Arrow (Prod RealNoNaN PosInfinity) True)
       & (Arrow (Prod PosInfinity (And RealNoNaN (Not PosInfinity))) False))]
  [(nop2-type =)
   (And* (Arrow (Prod SomeNaN Number) False)
       & (Arrow (Prod Number SomeNaN) False)
       & (Arrow (Prod RealZeroNoNaN RealZeroNoNaN) True)
       & (Arrow (Prod (And ExactNumber (Not RealZero)) RealZero) False)
       & (Arrow (Prod RealZero (And ExactNumber (Not RealZero))) False)
       & (Arrow (Prod (And ExactNumber (Not One)) One) False)
       & (Arrow (Prod One (And ExactNumber (Not One))) False)
       & (Arrow (Prod (And ExactNumber (Not Byte)) Byte) False)
       & (Arrow (Prod Byte (And ExactNumber (Not Byte))) False)
       & (Arrow (Prod (And ExactNumber (Not Index)) Index) False)
       & (Arrow (Prod Index (And ExactNumber (Not Index))) False)
       & (Arrow (Prod (And ExactNumber (Not Fixnum)) Fixnum) False)
       & (Arrow (Prod Fixnum (And ExactNumber (Not Fixnum))) False)
       & (Arrow (Prod (And ExactNumber (Not Integer)) Integer) False)
       & (Arrow (Prod Integer (And ExactNumber (Not Integer))) False)
       & (Arrow (Prod (And ExactNumber (Not Rational)) Rational) False)
       & (Arrow (Prod Rational (And ExactNumber (Not Rational))) False)
       & (Arrow (Prod NonposReal PosReal) False)
       & (Arrow (Prod PosReal NonposReal) False)
       & (Arrow (Prod NonnegReal NegReal) False)
       & (Arrow (Prod NegReal NonnegReal) False)
       & (Arrow (Prod Number Number) Boolean))]
  [(nop2-type expt)
   (And* (Arrow (Prod One Rational) One)
       & (Arrow (Prod Number Zero) One)
       & (Arrow (Prod Integer NonnegInteger) Integer)
       & (Arrow (Prod PosRational Integer) PosRational)
       & (Arrow (Prod NonnegRational Integer) NonnegRational)
       & (Arrow (Prod Rational Integer) Rational)
       & (Arrow (Prod NonnegFloat Real) (Or NonnegFloat One))
       & (Arrow (Prod PosReal NonnegFloat) (Or NonnegFloat One))
       & (Arrow (Prod Float (Or NegFixnum PosFixnum)) Float)
       & (Arrow (Prod Float Float) (Or Float FloatComplex))
       & (Arrow (Prod SingleFloat (Or NegFixnum PosFixnum)) SingleFloat)
       & (Arrow (Prod SingleFloat SingleFloat) (Or SingleFloat SingleFloatComplex))
       & (Arrow (Prod PosReal Real) NonnegReal)
       & (Arrow (Prod NonnegReal Real) Real)
       & (Arrow (Prod InexactReal InexactReal) (Or InexactReal InexactComplex))
       & (Arrow (Prod Real NonnegInteger) Real)
       & (Arrow (Prod FloatComplex Float) (Or FloatComplex Float))
       & (Arrow (Prod FloatComplex InexactReal) (Or FloatComplex InexactReal))
       & (Arrow (Prod FloatComplex InexactComplex) FloatComplex)
       & (Arrow (Prod SingleFloatComplex SingleFloatComplex) SingleFloatComplex)
       & (Arrow (Prod SingleFloatComplex SingleFloat) (Or SingleFloatComplex SingleFloat))
       & (Arrow (Prod InexactComplex InexactComplex) InexactComplex)
       & (Arrow (Prod Number Number) Number))]
  [(nop2-type quotient)
   (And* (Arrow (Prod PosFixnum One) PosFixnum)
       & (Arrow (Prod NegFixnum One) NegFixnum)
       & (Arrow (Prod Byte NonnegInteger) Byte)
       & (Arrow (Prod Index NonnegInteger) Index)
       & (Arrow (Prod NonposFixnum NonnegFixnum) NonposFixnum)
       & (Arrow (Prod NonnegFixnum Integer) Fixnum)
       & (Arrow (Prod NonnegInteger NonnegInteger) NonnegInteger)
       & (Arrow (Prod NonnegInteger NonposInteger) NonposInteger)
       & (Arrow (Prod NonposInteger NonnegInteger) NonposInteger)
       & (Arrow (Prod NonposInteger NonposInteger) NonnegInteger))]
  [(nop2-type modulo)
   (And* (Arrow (Prod One One) Zero)
       & (Arrow (Prod Integer Byte) Byte)
       & (Arrow (Prod Byte NonnegInteger) Byte)
       & (Arrow (Prod Integer Index) Index)
       & (Arrow (Prod Index NonnegInteger) Index)
       & (Arrow (Prod Integer NonnegFixnum) NonnegFixnum)
       & (Arrow (Prod NonnegFixnum NonnegInteger) NonnegFixnum)
       & (Arrow (Prod Integer NonnegInteger) NonnegInteger)
       & (Arrow (Prod NonnegInteger NonnegInteger) NonnegInteger)
       & (Arrow (Prod Integer NonposFixnum) NonposFixnum)
       & (Arrow (Prod Integer NonposInteger) NonposInteger)
       & (Arrow (Prod Integer Fixnum) Fixnum)
       & (Arrow (Prod Integer Integer) Integer))])
